<p style="color:#FFF; background:#07D; padding:12px; font-size:20px; font-style:italic; text-align:center">
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right">schlick[at]u-bordeaux.fr</span>
<span style="font-size:48px; font-style:normal"><b>PACKAGE : PANDAS</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Version 2022-06</span>
<span style="width:49%; display:inline-block; text-align:right">Licence CC-BY-NC-ND</span></p>

Le package [**pandas**](http://pandas.pydata.org) (contraction de ***Panel Data Analysis***) fournit à Python des outils pour manipuler des tableaux de données de toute nature. Le package **pandas** est presque toujours utilisé en collaboration avec le package **numpy**, chacun d'eux fournissant des outils de traitement spécifiques. Plus précisément, il y a quatre différences fondamentales entre les fonctionnalités offertes par  **numpy** et celles offertes par **pandas** :

- Le package **numpy** fournit un seul type de conteneur (appelé **`array`**) qui peut avoir un nombre quelconque de dimensions, alors que le package **pandas** fournit trois types de conteneurs : un conteneur 1D (appelé **`series`**), un conteneur 2D (appelé **`dataframe`**) et un conteneur 3D (appelé **`panel`**). Il n'y a pas de traduction française "officielle" pour le nom des conteneurs fournis par **pandas**. Dans ce cours, nous allons utiliser les termes **série** pour **`series`**, **table** pour **`dataframe`** et **classeur** pour **`panel`**.
- une matrice **numpy** doit avoir toutes ses données du même type, ce qui est également le cas pour les séries **pandas**. Par contre, une table ou un classeur **pandas** peut contenir un nombre quelconque de type de données (habituellement on va avoir un type de données par série) 
- les dimensions d'une matrice **numpy** sont toujours indexées par des entiers démarrant à 0, alors que chaque dimension des conteneurs **pandas** possède un index de nature arbitraire pour identifier ses éléments (on peut considérer un index comme un équivalent des clés d'un dictionnaire) 
- même si les matrices **numpy** peuvent contenir des cases vides (identifiées par la valeur **`NaN`**), celles-ci vont empêcher l'utilisation d'un grand nombre d'outils **numpy** qui nécessitent des matrices à données complètes. A l'inverse, **pandas** sait gérer beaucoup mieux les données partielles, et propose plusieurs outils pour traiter automatiquement les données manquantes, ce qui le rend beaucoup souple pour le traitement des données ***dans la vraie vie***, où les bases de données sans trous ou sans données aberrantes sont extrêmement rares.

La manière la plus intuitive pour comprendre les conteneurs fournis par **pandas** est de se référer à l'***organisation des données dans un tableur***, tel que *Microsoft Excel, Google Sheets, LibreOffice Calc* ou autre : l'ensemble des données stockées dans le classeur complet manipulé par le tableur correspond au type **`panel`** , les données stockées dans un onglet spécifique du classeur correspond au type **`dataframe`** , et enfin, les données stockées dans une colonne d'un des onglets correspond au type **`series`**.

La documentation complète du package se trouve sur le site [**pandas.org**](https://pandas.pydata.org/docs/user_guide), mais elle est également directement disponible dans le menu `Help` de l'interface Jupyter. Ce notebook a pour objet de faire un tour d'horizon rapide et de montrer les fonctionnalités les plus utiles de **matplotlib** dans le cadre d'une utilisation au sein de l'environnement Jupyter.

> **Remarque importante :**  Dans les versions récentes de **pandas**, le conteneur 3D **`panel`** (qui était pourtant à la base du nom du package) a été supprimé car il n'apportait pas beaucoup plus de fonctionnalités qu'un simple dictionnaire Python regroupant une série de conteneurs 2D **`dataframe`**. La suppression de ce conteneur 3D a été motivée par l'inclusion dans **pandas** d'un mécanisme d'indexation très puissant, appelé **`MultiIndex`**, permettant de créer des structures hiérarchiques de dimensions arbitraires. Etant donnée sa complexité, la mise en oeuvre des **`MultiIndex`** ne sera pas détaillée dans ce cours, qui se contentera de regrouper des tables en utilisant un dictionnaire Python ou un vecteur **numpy** lorsqu'une troisième dimension sera nécessaire.
---
On importe habituellement le package **pandas** par le biais d'un alias court, avec la commande suivante :
> `import pandas as pd`

In [1]:
import numpy as np # import du package 'numpy' avec alias 'np' 
import pandas as pd # import du package 'pandas' avec alias 'pd'
from SRC.tools import show # import de la fonction 'show' permettant de simplifier certaines explications

<h2 style="padding:16px; color:#FFF; background:#07D">A - Création et accès aux séries et aux tables</h2>

### 1 - Création de séries

Dans la terminologie de **pandas**, une série (***series***) est un conteneur ordonné 1D dont l'accès aux éléments peut s'effectuer soit par leur position (comme c'est le cas pour les listes en Python) soit par un index spécifique associé à ces éléments (comme c'est le cas pour les dictionnaires en Python). Néanmoins, à la différence des listes et des dictionnaires standards, tous les éléments d'une série doivent être de même nature, comme c'est le cas pour les matrices **numpy**.

In [2]:
vec = [0, 50, 150, 300, 500] # création d'un vecteur de test (liste 1D standard)
show("vec")

vec = [0, 50, 150, 300, 500]


In [3]:
a = pd.Series(vec) # création d'une série à partir du vecteur de test
show("a#;; a.values; a.index; a.index.values") # par défaut, les séries ont un index de type 'RangeIndex'

a =
0      0
1     50
2    150
3    300
4    500
dtype: int64

a.values = [  0  50 150 300 500]
a.index = RangeIndex(start=0, stop=5, step=1)
a.index.values = [0 1 2 3 4]


Avec l'index de type **`RangeIndex`** créé par défaut, une série se comporte globalement comme un vecteur **numpy** : on peut accéder à ses éléments soit par indice, soit par tranche, soit par énumération, soit par prédicat. 

In [4]:
show("a[1];") # accès par indice
show("a[1:4]#;") # accès par tranche d'indices
show("a[[4,2,1]]#;") # accès par énumeration (ATTENTION : il faut une liste pas un tuple)
show("a[a > 200]#") # accès par prédicat

a[1] = 50

a[1:4] =
1     50
2    150
3    300
dtype: int64

a[[4,2,1]] =
4    500
2    150
1     50
dtype: int64

a[a > 200] =
3    300
4    500
dtype: int64


---
On peut modifier le comportement d'une série, on choisissant un autre type d'index :

In [5]:
b = pd.Series(vec, index=[4,2,5,1,8]) # on définit manuellement un index composé d'entiers non ordonnés
#b = pd.Series(dict(zip([4,2,5,1,8], vec))) # solution alternative à base de dictionnaire
show("b#;; b.values; b.index; b.index.values")

b =
4      0
2     50
5    150
1    300
8    500
dtype: int64

b.values = [  0  50 150 300 500]
b.index = Int64Index([4, 2, 5, 1, 8], dtype='int64')
b.index.values = [4 2 5 1 8]


> **ATTENTION :** l'utilisation d'index de type **`IntIndex`** nécessite une ***attention particulière*** car cela implique une utilisation parfois contre-intuitive qui peut être source de nombreuses erreurs. Comme on
peut le constater ci-dessous, **`b[n]`** utilise les valeurs de l'index, mais **`b[m:n]`** utilise les valeurs des positions :

In [6]:
show("b[1];") # accès par indice (ATTENTION : on utilise les valeurs de l'index)
show("b[1:4]#;") # accès par tranche (ATTENTION : on utilise les valeurs des positions)
show("b[[4,2,1]]#;") # accès par énumération (on utilise à nouveau les valeurs de l'index)
show("b[b > 200]#") # accès par prédicat

b[1] = 300

b[1:4] =
2     50
5    150
1    300
dtype: int64

b[[4,2,1]] =
4      0
2     50
1    300
dtype: int64

b[b > 200] =
1    300
8    500
dtype: int64


---
Une bien meilleure option est d'utiliser un index à base de chaînes de caractères, appelés ***labels*** :

In [7]:
c = pd.Series(vec, index=['A','B','C','D','E']) # on définit un index composé de labels
#c = pd.Series(dict(zip('ABCDE', vec))) # solution alternative à base de dictionnaire
show("c#;; c.values; c.index; c.index.values")

c =
A      0
B     50
C    150
D    300
E    500
dtype: int64

c.values = [  0  50 150 300 500]
c.index = Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
c.index.values = ['A' 'B' 'C' 'D' 'E']


Avec un index à base de labels, le comportement devient très souple et très intuitif :
- on peut utiliser des indices ou des tranches, aussi bien sur les positions que sur les labels
- on peut même utiliser la notation pointée pour accéder à un élément d'une série via son label

In [8]:
show("c[1];") # accès par position
show("c['D'];") # accès par label
show("c.D;") # accès par attribut (via la notation pointée)
show("c[1:4]#;") # accès par tranche de positions
show("c['B':'D']#;") # accès par tranche de labels (ATTENTION : 2 bornes incluses)
show("c[[4,2,1]]#;") # accès par énumération de positions
show("c[['E','C','B']]#;") # accès par énumération de labels
show("c[c > 200]#") # accès par prédicat

c[1] = 50

c['D'] = 300

c.D = 300

c[1:4] =
B     50
C    150
D    300
dtype: int64

c['B':'D'] =
B     50
C    150
D    300
dtype: int64

c[[4,2,1]] =
E    500
C    150
B     50
dtype: int64

c[['E','C','B']] =
E    500
C    150
B     50
dtype: int64

c[c > 200] =
D    300
E    500
dtype: int64


> **Note :** contrairement aux tranches de positions, une tranche de labels ***inclut les deux bornes de l'intervalle***

> **Note :** la notation pointée ne fonctionne que si les labels n'utilisent que les 63 caractères autorisés
pour un identificateur Python : `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_`
---
Aussi bien les données que les index d'une série **pandas** peuvent également être définis à partir de vecteurs **numpy** :

In [9]:
d = pd.Series(np.random.randint(0, 1000, 11)) # utilisation de l'index par défaut
show("d#;; d.values; d.index.values")

d =
0     997
1     215
2     605
3     663
4      16
5     689
6     990
7     709
8     955
9     604
10    568
dtype: int32

d.values = [997 215 605 663  16 689 990 709 955 604 568]
d.index.values = [ 0  1  2  3  4  5  6  7  8  9 10]


In [10]:
d.index = np.linspace(0,1,11) # on peut modifier l'index d'une série à tout moment
show("d#;; d.values; d.index; d.index.values")

d =
0.0    997
0.1    215
0.2    605
0.3    663
0.4     16
0.5    689
0.6    990
0.7    709
0.8    955
0.9    604
1.0    568
dtype: int32

d.values = [997 215 605 663  16 689 990 709 955 604 568]
d.index = Float64Index([                0.0,                 0.1,                 0.2,
              0.30000000000000004,                 0.4,                 0.5,
               0.6000000000000001,  0.7000000000000001,                 0.8,
                              0.9,                 1.0],
             dtype='float64')
d.index.values = [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


> **ATTENTION :** l'utilisation d'index de type **`FloatIndex`** est ***fortement déconseillée*** car les erreurs d'arrondis entre stockage binaire et affichage décimal, vont empêcher l'accès à certaines données.
On peut voir ci-dessous que l'indice 0.3 n'existe pas car il est stocké comme 0.30000000000000004 :

In [11]:
show("d[0.1];") # la valeur 0.1 existe dans l'index
show("d[0.35:0.85]#;") # on peut utiliser des valeurs intermédiaires pour les tranches
#show("d[0.3]") # la valeur 0.3 n'existe pas dans l'index (enlever le commentaire pour générer l'erreur)
show("0.3 in d.index; 0.30000000000000004 in d.index") # origine du problème

d[0.1] = 215

d[0.35:0.85] =
0.4     16
0.5    689
0.6    990
0.7    709
0.8    955
dtype: int32

0.3 in d.index = False
0.30000000000000004 in d.index = True


---
Pour manipuler des valeurs réelles dans un index, il est préférable de créer un **`IntervalIndex`**
qui permet d'associer un intervalle de valeurs à chaque indice, plutôt qu'une valeur unique. Cela s'avère particulièrement utile lorsque l'on doit réaliser un partitionnement ou un regroupement de données :

In [12]:
intervals = pd.interval_range(0, 10, freq=2.5, closed='left') # closed : left|right|both|neither
#intervals = pd.interval_range(0, 100, 5, closed='both')
e = pd.Series(np.random.rand(intervals.size), index=intervals)
show("e#;; e.values; e.index")

e =
[0.0, 2.5)     0.453512
[2.5, 5.0)     0.077991
[5.0, 7.5)     0.497028
[7.5, 10.0)    0.572682
dtype: float64

e.values = [0.45351186 0.07799097 0.4970281  0.57268224]
e.index = IntervalIndex([[0.0, 2.5), [2.5, 5.0), [5.0, 7.5), [7.5, 10.0)], dtype='interval[float64, left]')


In [13]:
show("e[2.4999999]; e[2.5]; e[2.5000001];") # l'intervalle est respecté selon la valeurs de l'indice
show("e[1:3]#;") # une tranche d'entiers utilise les positions
show("e[3.0:5.5]#") # une tranche de réels utilise les intervalles

e[2.4999999] = 0.4535118562898216
e[2.5] = 0.07799096599935296
e[2.5000001] = 0.07799096599935296

e[1:3] =
[2.5, 5.0)    0.077991
[5.0, 7.5)    0.497028
dtype: float64

e[3.0:5.5] =
[2.5, 5.0)    0.077991
[5.0, 7.5)    0.497028
dtype: float64


---
Dans le même ordre d'idée, les types **`DatetimeIndex`** et **`TimedeltaIndex`** permettent de créer des index spécifiques pour les séries temporelles, qui seront définis par une date/heure de début, un nombre de périodes, et une fréquence pour la génération des valeurs temporelles. Il est possible d'utiliser les symboles suivants pour définir la fréquence :

**`N`** = nanoseconde, **`U`** = microseconde, **`L`** = milliseconde, **`S`** = seconde, **`T`** = minute,
**`H`** = heure,

**`D`** = jour, **`W`** ou **`W-day`** = semaine, **`M`** ou **`MS`** = mois, **`Q`** ou **`QS`** = trimestre, **`Y`** ou **`YS`** = année

> **Note :** Les dates générées pour **M**, **Q** et **Y** correspondent au dernier jour de la période concernée, alors que les dates pour **MS**, **QS** et **YS** correspondent au premier jour (le suffixe **S** signifie ***start***). De même, les dates générées par **W** correspondent au dimanche (dernier jour de la semaine) mais on peut choisir le jour en utilisant **W-*day*** avec ***day*** pouvant prendre les valeurs suivantes : **`MON/TUE/WED/THU/FRI/SAT/SUN`**

In [14]:
index = pd.date_range('2000-01-01', periods=6, freq='MS') # création d'un index avec fréquence mensuelle
#index = pd.date_range('now', periods=6, freq='W-SAT').round('D') # idem avec fréquence hebdomadaire (samedi)
#index = pd.timedelta_range('0S', periods=7, freq='5S').round('S') # idem avec un intervalle de 5 secondes
#index = pd.timedelta_range('15H', periods=9, freq='1H30T').round('T') # idem avec un intervalle de 1H30
f = pd.Series(np.random.rand(index.size), index=index)
show("f#;; f.values#;; f.index#")

f =
2000-01-01    0.802855
2000-02-01    0.397091
2000-03-01    0.289506
2000-04-01    0.876712
2000-05-01    0.312441
2000-06-01    0.509264
Freq: MS, dtype: float64

f.values =
[0.8028549  0.39709123 0.28950577 0.87671158 0.3124415  0.50926404]

f.index =
DatetimeIndex(['2000-01-01', '2000-02-01', '2000-03-01', '2000-04-01',
               '2000-05-01', '2000-06-01'],
              dtype='datetime64[ns]', freq='MS')


In [15]:
show("f[1];") # un indice entier utilise les positions
show("f[1:4]#;") # idem pour les tranches d'entiers
show("f['2000-02-01']#;") # un indice chaîne de caractères utilise les dates
show("f['2000-02':'2000-04']#") # idem pour les tranches de chaînes

f[1] = 0.39709123418228043

f[1:4] =
2000-02-01    0.397091
2000-03-01    0.289506
2000-04-01    0.876712
Freq: MS, dtype: float64

f['2000-02-01'] =
0.39709123418228043

f['2000-02':'2000-04'] =
2000-02-01    0.397091
2000-03-01    0.289506
2000-04-01    0.876712
Freq: MS, dtype: float64


---
### 2 - Création de tables

Dans la terminologie de **pandas**, une table (***dataframe***) est un conteneur 2D qui est obtenu en agglomérant un ensemble de séries possédant toutes le même index. La convention usuelle est de considérer que chaque série représente une colonne de la table résultante (même si on peut évidemment appliquer l'opérateur de transposition si la configuration inverse est préférable pour un jeu de données particulier)

In [16]:
mat = [[1,-2,3,-4], [-5,6,-7,8], [9,-10,11,-12]] # création d'une matrice de test (liste 2D standard)
show("mat")

mat = [[1, -2, 3, -4], [-5, 6, -7, 8], [9, -10, 11, -12]]


In [17]:
aa = pd.DataFrame(mat) # création d'une table à partir de la matrice de test
aa # la table pandas est affichée dans le notebook sous la forme d'une table HTML

,0,1,2,3
0,1,-2,3,-4
1,-5,6,-7,8
2,9,-10,11,-12


In [18]:
# les données d'une table 'pandas' sont stockées dans l'attribut 'values' qui est une matrice 'numpy'
show("aa#;; aa.ndim; aa.shape; aa.size;; aa.values#; aa.values.nbytes; aa.values.dtype")

aa =
   0   1   2   3
0  1  -2   3  -4
1 -5   6  -7   8
2  9 -10  11 -12

aa.ndim = 2
aa.shape = (3, 4)
aa.size = 12

aa.values =
[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]
aa.values.nbytes = 96
aa.values.dtype = int64


In [19]:
# par défaut, les lignes et les colonnes d'une table 'pandas' ont un index de type 'RangeIndex'
show("aa.index; aa.index.values; aa.columns; aa.columns.values")

aa.index = RangeIndex(start=0, stop=3, step=1)
aa.index.values = [0 1 2]
aa.columns = RangeIndex(start=0, stop=4, step=1)
aa.columns.values = [0 1 2 3]


---
Une des caractéristiques particulières du système d'indexation utilisé par les tables **pandas** est qu'il est assymétrique : les ***indices s'appliquent aux colonnes***, les ***tranches d'indices s'appliquent aux lignes***. C'est un peu déroutant au départ, mais à l'usage, il s'avère que ce choix est judicieux par rapport aux manipulations habituellement effectuées sur une telle table. Si l'on souhaite accéder à une ligne unique ou à une tranche de colonnes, la manière la plus simple est d'appliquer une transposition à la table, ou alors utiliser les attributs **`.loc`** et **`.iloc`** créés pour cet usage :

In [20]:
show("aa[1]#;") # accès à une colonne 
show("aa.T[1]#;") # accès à une ligne
show("aa.iloc[1]#;") # idem avec 'iloc' : aa.T[1] <=> aa.iloc[1]
show("aa[1:3]#;") # accès à une tranche de lignes
show("aa.T[1:3].T#") # accès à une tranche de colonnes
show("aa.iloc[:,1:3]#") # idem avec 'iloc': aa.T[1:3].T <=> aa.iloc[:,1:3]

aa[1] =
0    -2
1     6
2   -10
Name: 1, dtype: int64

aa.T[1] =
0   -5
1    6
2   -7
3    8
Name: 1, dtype: int64

aa.iloc[1] =
0   -5
1    6
2   -7
3    8
Name: 1, dtype: int64

aa[1:3] =
   0   1   2   3
1 -5   6  -7   8
2  9 -10  11 -12

aa.T[1:3].T =
    1   2
0  -2   3
1   6  -7
2 -10  11
aa.iloc[:,1:3] =
    1   2
0  -2   3
1   6  -7
2 -10  11


---
Comme pour les matrices **numpy**, on peut utiliser l'accès par énumération ou par prédicat pour les tables **pandas**, avec néanmoins deux différences notables :

- L'énumération doit nécessairement utiliser une liste d'indices (et non un tuple)
- Les données de la table qui ne vérifient pas le prédicat ne sont pas supprimées dans les valeurs retournées, mais sont remplacées par **`NaN`** (***Not-A-Number***)

In [21]:
show("aa[[3,1]]#;") # accès par énumération de colonnes
show("aa.iloc[[2,0]]#;") # accès par énumération de lignes
show("aa[aa % 5 != 0]#") # accès par prédicat

aa[[3,1]] =
    3   1
0  -4  -2
1   8   6
2 -12 -10

aa.iloc[[2,0]] =
   0   1   2   3
2  9 -10  11 -12
0  1  -2   3  -4

aa[aa % 5 != 0] =
     0    1   2   3
0  1.0 -2.0   3  -4
1  NaN  6.0  -7   8
2  9.0  NaN  11 -12


> **Remarque importante :** Chaque fois qu'une opération fait apparaître un élément **`NaN`** dans une série, tous les éléments de cette série sont convertis en **`float`**, car la valeur **`NaN`** fait partie de l'encodage des réels, selon la norme IEEE 754. Lorsqu'un **`NaN`** apparait dans une table, seules les colonnes concernées sont converties en **`float`**. On peut le constater dans la table ci-dessus : les colonnes 0 et 1 contiennent un **`NaN`** et sont donc converties en **`float`**, alors que les colonnes 2 et 3
restent de type **`int`**
---
Il est très rare de garder l'index numérique par défaut pour les colonnes d'une table **pandas**. En effet, comme ces colonnes correspondent presque toujours à des séries, on va généralement attribuer un ***label*** à chaque colonne pour indiquer la nature des valeurs qui s'y trouvent, comme on le fait classiquement dans un tableur :

In [22]:
bb = pd.DataFrame(mat, columns=list('ABCD'))
bb

,A,B,C,D
0,1,-2,3,-4
1,-5,6,-7,8
2,9,-10,11,-12


In [23]:
# le type de données utilisé pour les labels est le type 'object'
show("bb#;; bb.values#; bb.index; bb.index.values; bb.columns; bb.columns.values")

bb =
   A   B   C   D
0  1  -2   3  -4
1 -5   6  -7   8
2  9 -10  11 -12

bb.values =
[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]
bb.index = RangeIndex(start=0, stop=3, step=1)
bb.index.values = [0 1 2]
bb.columns = Index(['A', 'B', 'C', 'D'], dtype='object')
bb.columns.values = ['A' 'B' 'C' 'D']


Avec des index de types différents, l'assymétrie des lignes et des colonnes semble plus naturelle. Et à nouveau, on bénéficie d'un accès par attribut, utilisant la notation pointée pour accéder à une colonne directement par son label (d'où l'intérêt d'***utiliser des labels qui ne contiennent que les 63 caractères autorisés pour les identificateurs*** en Python) :

In [24]:
show("bb['B']#;") # accès à une colonne par label
show("bb.B#;") # idem à une colonne par attribut (via la notation pointée)
show("bb.T[1]#;") # accès à une ligne par position <=> bb.iloc[1]
show("bb[1:3]#;") # accès à une tranche de ligne par positions
show("bb.T['B':'D'].T#") # accès à une tranche de colonne par labels <=> bb.loc[:,'B':'D']

bb['B'] =
0    -2
1     6
2   -10
Name: B, dtype: int64

bb.B =
0    -2
1     6
2   -10
Name: B, dtype: int64

bb.T[1] =
A   -5
B    6
C   -7
D    8
Name: 1, dtype: int64

bb[1:3] =
   A   B   C   D
1 -5   6  -7   8
2  9 -10  11 -12

bb.T['B':'D'].T =
    B   C   D
0  -2   3  -4
1   6  -7   8
2 -10  11 -12


---
Utiliser des labels pour les colonnes et des numéros pour les lignes est de très loin l'utilisation la plus classique des tables **pandas** : comme les séries mises en colonnes dans une table doivent toutes partager le même index, choisir un index de type **`RangeIndex`** consistant à numéroter les lignes, est effectivement un moyen simple pour identifier sans ambiguité les éléments de chaque série. Néanmoins, il est parfois judicieux d'utiliser un index plus élaboré pour les lignes de la table : en particulier, les index de type **`IntervalIndex`** ou **`DatetimeIndex`** sont utiles dans de nombreuses situations concrètes :

In [25]:
dates, labels = pd.date_range('2000-01-01', periods=6, freq='MS'), list('ABCDEF')
data = np.random.normal(0, 5, (6,6)) + [range(10, 120, 20)]
cc = pd.DataFrame(data, index=dates, columns=labels)
cc

,A,B,C,D,E,F
2000-01-01,14.405763,34.530469,46.800217,71.007212,86.913121,112.710064
2000-02-01,9.712673,24.921771,45.605942,75.888264,90.788889,99.687241
2000-03-01,-1.496487,30.159783,57.719180,67.761867,87.062249,110.616368
2000-04-01,10.818431,35.572674,48.285931,71.562775,88.213840,112.910178
2000-05-01,-0.535452,33.638460,48.798429,72.209626,89.585116,108.870119
2000-06-01,3.453829,34.731492,57.557638,65.176539,85.781936,117.511746


In [26]:
# L'accès aux colonnes (label ou tranche de labels) est inchangé par rapport à la table précédente
show("cc['B']#;") # accès à une colonne par label
show("cc.B#;") # accès à une colonne par attribut
show("cc.T['B':'E'].T#") # accès à une tranche de colonnes

cc['B'] =
2000-01-01    34.530469
2000-02-01    24.921771
2000-03-01    30.159783
2000-04-01    35.572674
2000-05-01    33.638460
2000-06-01    34.731492
Freq: MS, Name: B, dtype: float64

cc.B =
2000-01-01    34.530469
2000-02-01    24.921771
2000-03-01    30.159783
2000-04-01    35.572674
2000-05-01    33.638460
2000-06-01    34.731492
Freq: MS, Name: B, dtype: float64

cc.T['B':'E'].T =
                    B          C          D          E
2000-01-01  34.530469  46.800217  71.007212  86.913121
2000-02-01  24.921771  45.605942  75.888264  90.788889
2000-03-01  30.159783  57.719180  67.761867  87.062249
2000-04-01  35.572674  48.285931  71.562775  88.213840
2000-05-01  33.638460  48.798429  72.209626  89.585116
2000-06-01  34.731492  57.557638  65.176539  85.781936


In [27]:
# par contre, on dispose d'une plus grande variété pour l'accès aux lignes
show("cc.T['2000-03-01']#;") # accès à une ligne par date <=> cc.loc['2000-03-01']
show("cc.iloc[2]#;") # accès à une ligne par position
show("cc['20000301':'20000501']#;") # accès à une tranche de lignes par dates
show("cc[2:5]#;") # accès à une tranche de lignes par positions

cc.T['2000-03-01'] =
A     -1.496487
B     30.159783
C     57.719180
D     67.761867
E     87.062249
F    110.616368
Name: 2000-03-01 00:00:00, dtype: float64

cc.iloc[2] =
A     -1.496487
B     30.159783
C     57.719180
D     67.761867
E     87.062249
F    110.616368
Name: 2000-03-01 00:00:00, dtype: float64

cc['20000301':'20000501'] =
                    A          B          C          D          E           F
2000-03-01  -1.496487  30.159783  57.719180  67.761867  87.062249  110.616368
2000-04-01  10.818431  35.572674  48.285931  71.562775  88.213840  112.910178
2000-05-01  -0.535452  33.638460  48.798429  72.209626  89.585116  108.870119

cc[2:5] =
                    A          B          C          D          E           F
2000-03-01  -1.496487  30.159783  57.719180  67.761867  87.062249  110.616368
2000-04-01  10.818431  35.572674  48.285931  71.562775  88.213840  112.910178
2000-05-01  -0.535452  33.638460  48.798429  72.209626  89.585116  108.870119



---

Toutes les tables définies ci-dessus possèdent le même type de données pour chacune des cellules, ce qui les rend assez proches des matrices fournies par **numpy**. La fonctionnalité la plus intéressante des tables fournies par le package **pandas** est, au contraire, de pouvoir mixer des données de nature arbitraire, en utilisant une série différente pour chaque colonne. La manière la plus habituelle utilisée pour créer une variable de type **`dataframe`** est de fournir un dictionnaire Python, regroupant plusieurs séries, chacune étant associé avec un label de type chaîne :

In [28]:
dd = pd.DataFrame(dict(Name=[3*c for c in 'ABCDEF'], Model=pd.Categorical(2*['S','M','L']), Start=0,
     Stop=np.random.randint(0,100,(6,), dtype='u1'), Score=np.linspace(0, 3, 6), Test=dates.month > 3, 
     Date=dates, Delta=(pd.Timestamp('now') - dates).round('D')))
dd

,Name,Model,Start,Stop,Score,Test,Date,Delta
0,AAA,S,0,0,0.0,False,2000-01-01,8361 days
1,BBB,M,0,88,0.6,False,2000-02-01,8330 days
2,CCC,L,0,84,1.2,False,2000-03-01,8301 days
3,DDD,S,0,36,1.8,True,2000-04-01,8270 days
4,EEE,M,0,98,2.4,True,2000-05-01,8240 days
5,FFF,L,0,64,3.0,True,2000-06-01,8209 days


In [29]:
# l'index des lignes est un 'RangeIndex' par défaut, celui des colonnes est un 'Index' de labels
show("dd.index; dd.index.values; dd.columns; dd.columns.values")

dd.index = RangeIndex(start=0, stop=6, step=1)
dd.index.values = [0 1 2 3 4 5]
dd.columns = Index(['Name', 'Model', 'Start', 'Stop', 'Score', 'Test', 'Date', 'Delta'], dtype='object')
dd.columns.values = ['Name' 'Model' 'Start' 'Stop' 'Score' 'Test' 'Date' 'Delta']


In [30]:
# l'attribut 'dtypes' est une série 'pandas' contenant le type de données utilisé pour chaque colonne
show("dd.dtypes#")

dd.dtypes =
Name              object
Model           category
Start              int64
Stop               uint8
Score            float64
Test                bool
Date      datetime64[ns]
Delta    timedelta64[ns]
dtype: object


In [31]:
# n'importe quelle colonne peut être utilisée comme index pour les lignes (attention aux doublons !)
dd.index = dd.Date # on utilise la colonne 'Date' comme index
dd.index = dd.Name # on utilise la colonne 'Name' comme index
#dd.index = dd.Test # la colonne 'Test' est un mauvais choix à cause des doublons
dd.index.name = None # le label de l'index est inutile, donc on le supprime
dd # la colonne utilisée comme index n'est pas enlevée de la table

,Name,Model,Start,Stop,Score,Test,Date,Delta
AAA,AAA,S,0,0,0.0,False,2000-01-01,8361 days
BBB,BBB,M,0,88,0.6,False,2000-02-01,8330 days
CCC,CCC,L,0,84,1.2,False,2000-03-01,8301 days
DDD,DDD,S,0,36,1.8,True,2000-04-01,8270 days
EEE,EEE,M,0,98,2.4,True,2000-05-01,8240 days
FFF,FFF,L,0,64,3.0,True,2000-06-01,8209 days


<h2 style="padding:16px; color:#FFF; background:#07D">B - Manipulation des séries et des tables</h2>

Les séries et les tables **pandas** sont construites en se basant sur les vecteurs et matrices fournies par **numpy** (comme on l'a vu, les données sont stockées dans l'attribut **`values`** qui est de type **`array`**), donc les opérations et fonctions de **numpy** sont directement utilisables avec **pandas**.

Mais le package offre d'autres fonctionnalités particulièrement intéressantes dans le cadre des applications en Science des Données, dont on va faire un tour d'horizon rapide :

---
### 1 - Informations générales sur les données stockées


In [32]:
dd.head(3) # affichage des 'n' premières lignes (5 par défaut)

,Name,Model,Start,Stop,Score,Test,Date,Delta
AAA,AAA,S,0,0,0.0,False,2000-01-01,8361 days
BBB,BBB,M,0,88,0.6,False,2000-02-01,8330 days
CCC,CCC,L,0,84,1.2,False,2000-03-01,8301 days


In [33]:
dd.tail(3) # affichage des 'n' dernières lignes (5 par défaut)

,Name,Model,Start,Stop,Score,Test,Date,Delta
DDD,DDD,S,0,36,1.8,True,2000-04-01,8270 days
EEE,EEE,M,0,98,2.4,True,2000-05-01,8240 days
FFF,FFF,L,0,64,3.0,True,2000-06-01,8209 days


In [34]:
dd.describe() # statistiques descriptives sur chaque colonne à valeurs numériques

,Start,Stop,Score,Delta
count,6.0,6.000000,6.000000,6
mean,0.0,61.666667,1.500000,8285 days 04:00:00
std,0.0,37.361299,1.122497,56 days 17:09:17.293801904
min,0.0,0.000000,0.000000,8209 days 00:00:00
25%,0.0,43.000000,0.750000,8247 days 12:00:00
50%,0.0,74.000000,1.500000,8285 days 12:00:00
75%,0.0,87.000000,2.250000,8322 days 18:00:00
max,0.0,98.000000,3.000000,8361 days 00:00:00


In [35]:
dd.describe(include='all', datetime_is_numeric=True) # on force l'inclusion des colonnes non-numériques

,Name,Model,Start,Stop,Score,Test,Date,Delta
count,6,6,6.0,6.000000,6.000000,6,6,6
unique,6,3,NaN,NaN,NaN,2,NaN,NaN
top,AAA,L,NaN,NaN,NaN,False,NaN,NaN
freq,1,2,NaN,NaN,NaN,3,NaN,NaN
mean,NaN,NaN,0.0,61.666667,1.500000,NaN,2000-03-16 20:00:00,8285 days 04:00:00
min,NaN,NaN,0.0,0.000000,0.000000,NaN,2000-01-01 00:00:00,8209 days 00:00:00
25%,NaN,NaN,0.0,43.000000,0.750000,NaN,2000-02-08 06:00:00,8247 days 12:00:00
50%,NaN,NaN,0.0,74.000000,1.500000,NaN,2000-03-16 12:00:00,8285 days 12:00:00
75%,NaN,NaN,0.0,87.000000,2.250000,NaN,2000-04-23 12:00:00,8322 days 18:00:00
max,NaN,NaN,0.0,98.000000,3.000000,NaN,2000-06-01 00:00:00,8361 days 00:00:00


In [36]:
dd.sort_values(by='Stop') # tri (ascendant) selon une colonne

,Name,Model,Start,Stop,Score,Test,Date,Delta
AAA,AAA,S,0,0,0.0,False,2000-01-01,8361 days
DDD,DDD,S,0,36,1.8,True,2000-04-01,8270 days
FFF,FFF,L,0,64,3.0,True,2000-06-01,8209 days
CCC,CCC,L,0,84,1.2,False,2000-03-01,8301 days
BBB,BBB,M,0,88,0.6,False,2000-02-01,8330 days
EEE,EEE,M,0,98,2.4,True,2000-05-01,8240 days


In [37]:
dd.sort_values(by=['Model','Stop'], ascending=False) # tri (descendant) selon un groupe de colonnes
# les valeurs NaN sont toujours mise à la fin, en ascendant ou en descendant

,Name,Model,Start,Stop,Score,Test,Date,Delta
DDD,DDD,S,0,36,1.8,True,2000-04-01,8270 days
AAA,AAA,S,0,0,0.0,False,2000-01-01,8361 days
EEE,EEE,M,0,98,2.4,True,2000-05-01,8240 days
BBB,BBB,M,0,88,0.6,False,2000-02-01,8330 days
CCC,CCC,L,0,84,1.2,False,2000-03-01,8301 days
FFF,FFF,L,0,64,3.0,True,2000-06-01,8209 days


---
### 2 - Extraction de données

Parmi les opérations les plus fréquentes dans la manipulation des tables, figure l'extraction d'un sous-ensemble des données, soit sous la forme d'une zone rectangulaire (définie par une double tranche), soit sous la forme d'une sélection conjointe de lignes et de colonnes (définie par une double énumération). Avec le mécanisme d'indexation fourni par **pandas** toutes ces opérations sont très simples à mettre en oeuvre :

In [38]:
show("dd['CCC':'EEE'].T['Model':'Test'].T#;") # accès avec double tranche (dates + labels)
show("dd.loc['CCC':'EEE','Model':'Test']#;") # idem avec 'loc' (dates + labels)
show("dd.iloc[2:5,1:6]#;") # idem avec 'iloc' (double tranche de positions)

show("dd.T[['FFF','AAA','DDD']].T[['Date','Score','Model']]#;") # double énumération (dates + labels)
show("dd.loc[('FFF','AAA','DDD'),('Date','Score','Model')]#;") # idem avec 'loc' (dates + labels)
show("dd.iloc[[5,0,3],[6,4,1]]#") # idem avec 'iloc' (double énumération de positions)

dd['CCC':'EEE'].T['Model':'Test'].T =
    Model Start Stop Score   Test
CCC     L     0   84   1.2  False
DDD     S     0   36   1.8   True
EEE     M     0   98   2.4   True

dd.loc['CCC':'EEE','Model':'Test'] =
    Model  Start  Stop  Score   Test
CCC     L      0    84    1.2  False
DDD     S      0    36    1.8   True
EEE     M      0    98    2.4   True

dd.iloc[2:5,1:6] =
    Model  Start  Stop  Score   Test
CCC     L      0    84    1.2  False
DDD     S      0    36    1.8   True
EEE     M      0    98    2.4   True

dd.T[['FFF','AAA','DDD']].T[['Date','Score','Model']] =
          Date Score Model
FFF 2000-06-01   3.0     L
AAA 2000-01-01   0.0     S
DDD 2000-04-01   1.8     S

dd.loc[('FFF','AAA','DDD'),('Date','Score','Model')] =
          Date  Score Model
FFF 2000-06-01    3.0     L
AAA 2000-01-01    0.0     S
DDD 2000-04-01    1.8     S

dd.iloc[[5,0,3],[6,4,1]] =
          Date  Score Model
FFF 2000-06-01    3.0     L
AAA 2000-01-01    0.0     S
DDD 2000-04-01    1.8     S

In [39]:
show("dd[dd['Model'] == 'S']#;") # extraction des lignes vérifiant un prédicat
show("dd[dd['Model'] == 'S'][['Name','Score','Test']]#;") # idem avec sélection des colonnes
show("dd[dd['Model'] == 'S'].Score#") # idem avec sélection d'une colonne par attribut

dd[dd['Model'] == 'S'] =
    Name Model  Start  Stop  Score   Test       Date     Delta
AAA  AAA     S      0     0    0.0  False 2000-01-01 8361 days
DDD  DDD     S      0    36    1.8   True 2000-04-01 8270 days

dd[dd['Model'] == 'S'][['Name','Score','Test']] =
    Name  Score   Test
AAA  AAA    0.0  False
DDD  DDD    1.8   True

dd[dd['Model'] == 'S'].Score =
AAA    0.0
DDD    1.8
Name: Score, dtype: float64


---
### 3 - Insertion, Suppression et Modification de données

Pour éviter de détruire des données par erreur, la plupart des commandes de **pandas** qui suppriment ou modifient les données vont travailler sur une copie des données originelles, ce qui permet de tester sans risques les opérations à effectuer avant de les mettre concrètement en oeuvre. Ainsi la plupart des fonctions possède un argument booléen **`inplace`** (égal à **`False`** par défaut) qui indique si la fonction doit s'appliquer "sur place" ou sur une copie. Les commandes d'insertion de données, par contre, n'ont besoin de ce mécanisme, puisque les données existantes ne sont pas modifiées.

In [40]:
dd # rappel du contenu de la table

,Name,Model,Start,Stop,Score,Test,Date,Delta
AAA,AAA,S,0,0,0.0,False,2000-01-01,8361 days
BBB,BBB,M,0,88,0.6,False,2000-02-01,8330 days
CCC,CCC,L,0,84,1.2,False,2000-03-01,8301 days
DDD,DDD,S,0,36,1.8,True,2000-04-01,8270 days
EEE,EEE,M,0,98,2.4,True,2000-05-01,8240 days
FFF,FFF,L,0,64,3.0,True,2000-06-01,8209 days


In [41]:
dd['Rank'] = range(6,0,-1) # insertion d'une colonne complète
dd['Final'] = dd.Stop * dd.Score # insertion d'une colonne complète par combinaison
dd['Color'] = pd.Series(dict(AAA='blue', CCC='green', DDD='red')) # insertion d'une colonne incomplète
dd['Color-Name'] = dd.Color + '-' + dd.Name # insertion d'une colonne incomplète par combinaison
dd # note : la valeur NaN est "contagieuse" (elle se transmet à toute opération où elle est impliquée)

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color,Color-Name
AAA,AAA,S,0,0,0.0,False,2000-01-01,8361 days,6,0.0,blue,blue-AAA
BBB,BBB,M,0,88,0.6,False,2000-02-01,8330 days,5,52.8,NaN,NaN
CCC,CCC,L,0,84,1.2,False,2000-03-01,8301 days,4,100.8,green,green-CCC
DDD,DDD,S,0,36,1.8,True,2000-04-01,8270 days,3,64.8,red,red-DDD
EEE,EEE,M,0,98,2.4,True,2000-05-01,8240 days,2,235.2,NaN,NaN
FFF,FFF,L,0,64,3.0,True,2000-06-01,8209 days,1,192.0,NaN,NaN


In [42]:
del dd['Color-Name'] # suppression d'une colonne (sur place)
ee = dd.drop(columns=['Date','Delta']) # suppression d'un groupe de colonnes (sur copie)
ee
#dd.drop(columns=['Date','Delta'], inplace=True) # suppression d'un groupe de colonnes (sur place)
#dd

,Name,Model,Start,Stop,Score,Test,Rank,Final,Color
AAA,AAA,S,0,0,0.0,False,6,0.0,blue
BBB,BBB,M,0,88,0.6,False,5,52.8,NaN
CCC,CCC,L,0,84,1.2,False,4,100.8,green
DDD,DDD,S,0,36,1.8,True,3,64.8,red
EEE,EEE,M,0,98,2.4,True,2,235.2,NaN
FFF,FFF,L,0,64,3.0,True,1,192.0,NaN


In [43]:
dd.loc['ZZZ'] = dict(Name='ZZZ', Model='S', Start=1, Test=False, Color='white') # insertion d'une ligne
dd

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color
AAA,AAA,S,0,0.0,0.0,False,2000-01-01 00:00:00,8361 days 00:00:00,6.0,0.0,blue
BBB,BBB,M,0,88.0,0.6,False,2000-02-01 00:00:00,8330 days 00:00:00,5.0,52.8,NaN
CCC,CCC,L,0,84.0,1.2,False,2000-03-01 00:00:00,8301 days 00:00:00,4.0,100.8,green
DDD,DDD,S,0,36.0,1.8,True,2000-04-01 00:00:00,8270 days 00:00:00,3.0,64.8,red
EEE,EEE,M,0,98.0,2.4,True,2000-05-01 00:00:00,8240 days 00:00:00,2.0,235.2,NaN
FFF,FFF,L,0,64.0,3.0,True,2000-06-01 00:00:00,8209 days 00:00:00,1.0,192.0,NaN
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,NaN,NaN,white


In [44]:
ee = dd.drop(['CCC','DDD']) # suppression de lignes (sur copie)
ee

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color
AAA,AAA,S,0,0.0,0.0,False,2000-01-01 00:00:00,8361 days 00:00:00,6.0,0.0,blue
BBB,BBB,M,0,88.0,0.6,False,2000-02-01 00:00:00,8330 days 00:00:00,5.0,52.8,NaN
EEE,EEE,M,0,98.0,2.4,True,2000-05-01 00:00:00,8240 days 00:00:00,2.0,235.2,NaN
FFF,FFF,L,0,64.0,3.0,True,2000-06-01 00:00:00,8209 days 00:00:00,1.0,192.0,NaN
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,NaN,NaN,white


In [45]:
dd.drop('EEE', inplace=True) # suppression d'une ligne (sur place)
dd

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color
AAA,AAA,S,0,0.0,0.0,False,2000-01-01 00:00:00,8361 days 00:00:00,6.0,0.0,blue
BBB,BBB,M,0,88.0,0.6,False,2000-02-01 00:00:00,8330 days 00:00:00,5.0,52.8,NaN
CCC,CCC,L,0,84.0,1.2,False,2000-03-01 00:00:00,8301 days 00:00:00,4.0,100.8,green
DDD,DDD,S,0,36.0,1.8,True,2000-04-01 00:00:00,8270 days 00:00:00,3.0,64.8,red
FFF,FFF,L,0,64.0,3.0,True,2000-06-01 00:00:00,8209 days 00:00:00,1.0,192.0,NaN
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,NaN,NaN,white


Pour la modification individuelle d'un élément d'une table, il existe une erreur courante due au système d'indexation différent utilisé par **pandas** et **numpy** :

In [46]:
ee['FFF','Color'] = 'yellow' # ATTENTION : 'pandas' n'est pas 'numpy' !!!
ee

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color,"(FFF, Color)"
AAA,AAA,S,0,0.0,0.0,False,2000-01-01 00:00:00,8361 days 00:00:00,6.0,0.0,blue,yellow
BBB,BBB,M,0,88.0,0.6,False,2000-02-01 00:00:00,8330 days 00:00:00,5.0,52.8,NaN,yellow
EEE,EEE,M,0,98.0,2.4,True,2000-05-01 00:00:00,8240 days 00:00:00,2.0,235.2,NaN,yellow
FFF,FFF,L,0,64.0,3.0,True,2000-06-01 00:00:00,8209 days 00:00:00,1.0,192.0,NaN,yellow
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,NaN,NaN,white,yellow


In [47]:
dd.loc['FFF','Color'] = 'yellow'
dd

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color
AAA,AAA,S,0,0.0,0.0,False,2000-01-01 00:00:00,8361 days 00:00:00,6.0,0.0,blue
BBB,BBB,M,0,88.0,0.6,False,2000-02-01 00:00:00,8330 days 00:00:00,5.0,52.8,NaN
CCC,CCC,L,0,84.0,1.2,False,2000-03-01 00:00:00,8301 days 00:00:00,4.0,100.8,green
DDD,DDD,S,0,36.0,1.8,True,2000-04-01 00:00:00,8270 days 00:00:00,3.0,64.8,red
FFF,FFF,L,0,64.0,3.0,True,2000-06-01 00:00:00,8209 days 00:00:00,1.0,192.0,yellow
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,NaN,NaN,white


In [48]:
dd.loc['FFF','Color'] = np.nan # mettre 'np.nan' signifie effacer la donnée pour 'pan'
dd

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color
AAA,AAA,S,0,0.0,0.0,False,2000-01-01 00:00:00,8361 days 00:00:00,6.0,0.0,blue
BBB,BBB,M,0,88.0,0.6,False,2000-02-01 00:00:00,8330 days 00:00:00,5.0,52.8,NaN
CCC,CCC,L,0,84.0,1.2,False,2000-03-01 00:00:00,8301 days 00:00:00,4.0,100.8,green
DDD,DDD,S,0,36.0,1.8,True,2000-04-01 00:00:00,8270 days 00:00:00,3.0,64.8,red
FFF,FFF,L,0,64.0,3.0,True,2000-06-01 00:00:00,8209 days 00:00:00,1.0,192.0,NaN
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,NaN,NaN,white


In [49]:
show("dd['Color'].fillna('black')#;") # remplacement des NaN par une valeur constante
show("dd['Score'].fillna(dd['Score'].mean())#;") # remplacement des NaN par une valeur calculée
dd # la table est inchangée (pas de 'inplace=True')

dd['Color'].fillna('black') =
AAA     blue
BBB    black
CCC    green
DDD      red
FFF    black
ZZZ    white
Name: Color, dtype: object

dd['Score'].fillna(dd['Score'].mean()) =
AAA    0.00
BBB    0.60
CCC    1.20
DDD    1.80
FFF    3.00
ZZZ    1.32
Name: Score, dtype: float64



,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color
AAA,AAA,S,0,0.0,0.0,False,2000-01-01 00:00:00,8361 days 00:00:00,6.0,0.0,blue
BBB,BBB,M,0,88.0,0.6,False,2000-02-01 00:00:00,8330 days 00:00:00,5.0,52.8,NaN
CCC,CCC,L,0,84.0,1.2,False,2000-03-01 00:00:00,8301 days 00:00:00,4.0,100.8,green
DDD,DDD,S,0,36.0,1.8,True,2000-04-01 00:00:00,8270 days 00:00:00,3.0,64.8,red
FFF,FFF,L,0,64.0,3.0,True,2000-06-01 00:00:00,8209 days 00:00:00,1.0,192.0,NaN
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,NaN,NaN,white


In [50]:
show("dd['Color'].fillna(method='ffill')#;") # remplacement des NaN par la valeur précédente (forward fill)
show("dd['Color'].fillna(method='bfill')#;") # remplacement des NaN par la valeur suivante (backward fill)

dd['Color'].fillna(method='ffill') =
AAA     blue
BBB     blue
CCC    green
DDD      red
FFF      red
ZZZ    white
Name: Color, dtype: object

dd['Color'].fillna(method='bfill') =
AAA     blue
BBB    green
CCC    green
DDD      red
FFF    white
ZZZ    white
Name: Color, dtype: object



<h2 style="padding:16px; color:#FFF; background:#07D">C - Lecture et écriture sur disque</h2>

TODO

In [52]:
authors = pd.read_csv('TEST/test-CSV.csv') # lecture d'un fichier CSV et transformation en 'dataframe'
authors

,Nom,Prénom,Date de naissance,Lieu de naissance,Date de décès,Lieu de décès
0,Hugo,Victor,26/02/1802,Besançon,22/05/1885,Paris
1,Baudelaire,Charles,09/04/1821,Paris,31/08/1867,Paris
2,Rimbaud,Arthur,20/10/1854,Charleville,10/11/1891,Marseille


In [53]:
# tout caractère unicode (y compris l'espace) est autorisé pour les labels, mais la notation pointée
# 'authors.Date de décès' ne fonctionnera pas dans ce cas (il faut un identificateur Python valide)
authors['Date de décès']

0    22/05/1885
1    31/08/1867
2    10/11/1891
Name: Date de décès, dtype: object

In [54]:
authors.T.to_csv('TEST/Tost CSV.csv') # écriture d'un dataframe dans un fichier CSV

In [55]:
data = pd.read_csv('CSV/calendar.csv')
data.set_index('Month', inplace=True) # on utilise les valeurs de la colonne 'Month' en tant que labels
data.index.name = None # et on efface l'entête de cette colonne qui n'a plus d'utilité
data

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Jan,0,3,6,0,22,3,4,24,23,3,23,22,12,6,13,17
Feb,12,14,22,4,10,5,5,14,21,11,23,18,3,17,15,2
Mar,16,16,12,6,4,24,18,25,7,14,1,11,3,12,1,5
Avr,8,4,14,10,21,14,17,12,22,5,15,4,16,3,0,7
May,8,5,7,12,9,13,3,24,24,4,21,2,24,1,12,3
Jun,20,22,20,14,13,9,1,12,9,9,16,8,0,5,6,8
Jul,3,5,0,20,21,23,10,15,5,23,23,11,14,24,9,13
Aug,3,2,25,20,9,16,20,17,20,25,7,16,5,16,13,0
Sep,12,11,5,14,17,22,7,22,2,15,5,0,4,0,21,2
Oct,19,16,3,13,19,3,6,4,22,22,0,15,25,13,21,21
