<p style="color:white; background:#07D; padding:12px; font-size:20px; font-style:italic; text-align:center">
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right">schlick[at]u-bordeaux.fr</span>
<span style="font-size:48px; font-style:normal"><b>EXERCICES : NUMPY</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Version 2022-09</span>
<span style="width:49%; display:inline-block; text-align:right">Licence CC-BY-NC-ND</span></p>

L'objectif de cette feuille d'exercices est de voir comment mettre en oeuvre quelques unes des fonctionnalités fournies par le package **`numpy`**, basées sur l'utilisation du conteneur **`array`** et des fonctions universelles pour manipuler les données stockées dans ce conteneur. Avant de commencer cette feuille d'exercices, il est donc fortement recommandé de relire le notebook **05-Numpy.ipynb** qui contient les éléments de cours correspondants.

> **Remarque importante :** Pour bénéficier du gain de vitesse fourni par le mécanisme de **vectorisation** qu'offrent les fonctions universelles, il est primordial de raisonner uniquement en manipulations globales des vecteurs et des matrices, et ceci pour l'ensemble des traitements à effectuer. Par conséquent ***aucune boucle **`for`** ou **`while`** ne devra être utilisée dans aucun des exercices de cette feuille !***

In [ ]:
import numpy as np # import du package 'numpy' avec alias 'np'
from SRC.tools import show # import de la fonction 'show'

<h2 style="padding:16px; color:white; background:#07D">Exercice D1 - Création de matrices</h2>

Pour chacune des cellules de code  listées ci-dessous, remplacer la chaîne **`'TODO'`** par la commande Python permettant de créer la matrice multi-dimensionnelle affichée juste au-dessus de la cellule concernée. L'objectif est de trouver à chaque fois la manière la plus concise possible pour construire la matrice, sachant que chaque cellule de code peut se réduire à 1, 2 ou 3 appels de fonctions issues du package **`numpy`**

> **Note :** Faire attention à distinguer les matrices à valeurs réelles et les matrices à valeurs entières

---
```
a =
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
```

In [ ]:
a = 'TODO'; show('a#')

---
```
b =
[[ 0  1  1  1  1  1]
 [-1  0  1  1  1  1]
 [-1 -1  0  1  1  1]
 [-1 -1 -1  0  1  1]
 [-1 -1 -1 -1  0  1]
 [-1 -1 -1 -1 -1  0]]
```

In [ ]:
b = 'TODO'; show('b#')

---
```
c =
[[ 1  7 13 19 25 31]
 [ 2  8 14 20 26 32]
 [ 3  9 15 21 27 33]
 [ 4 10 16 22 28 34]
 [ 5 11 17 23 29 35]
 [ 6 12 18 24 30 36]]
```

In [ ]:
c = 'TODO'; show('c#')

---
```
d =
[[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799 6.45894113]
 [4.37587211 8.91773001 9.63662761 3.83441519 7.91725038 5.2889492 ]
 [5.68044561 9.25596638 0.71036058 0.871293   0.20218397 8.32619846]
 [7.78156751 8.70012148 9.78618342 7.99158564 4.61479362 7.80529176]
 [1.18274426 6.39921021 1.43353287 9.44668917 5.21848322 4.1466194 ]]
```
**Note :** la matrice contient des valeurs aléatoires, avec une distribution uniforme sur $[0,10[$

In [ ]:
np.random.seed(0) # on force toujours la même séquence aléatoire
d = 'TODO'; show('d#')

---
```
e =
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
```

In [ ]:
e = 'TODO'; show('e#')

---
```
f =
[[ True  True  True  True  True  True  True  True]
 [False False False False False False False False]
 [ True  True  True  True  True  True  True  True]
 [False False False False False False False False]
 [ True  True  True  True  True  True  True  True]]
```

In [ ]:
f = 'TODO'; show('f#')

---
```
g =
[[-25  24 -23  22 -21]
 [ 20 -19  18 -17  16]
 [-15  14 -13  12 -11]
 [ 10  -9   8  -7   6]
 [ -5   4  -3   2  -1]]
```

In [ ]:
g = 'TODO'; show('g#')

---
```
h =
[[4.56 7.89 7.89 7.89 7.89 7.89]
 [1.23 4.56 7.89 7.89 7.89 7.89]
 [1.23 1.23 4.56 7.89 7.89 7.89]
 [1.23 1.23 1.23 4.56 7.89 7.89]
 [1.23 1.23 1.23 1.23 4.56 7.89]
 [1.23 1.23 1.23 1.23 1.23 4.56]]
```

In [ ]:
h = 'TODO'; show('h#')

---
```
i =
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 1 2 2 2 2 2 2 2 2]
 [0 1 2 3 3 3 3 3 3 3]
 [0 1 2 3 4 4 4 4 4 4]
 [0 1 2 3 4 5 5 5 5 5]
 [0 1 2 3 4 5 6 6 6 6]
 [0 1 2 3 4 5 6 7 7 7]
 [0 1 2 3 4 5 6 7 8 8]
 [0 1 2 3 4 5 6 7 8 9]]
```

In [ ]:
i = 'TODO'; show('i#')

---
```
j =
[[1.54264129 0.0415039  1.26729647 1.49760777 0.99701402 0.44959329]
 [2.39612573 3.52106142 2.33822167 2.17667963 3.37071964 3.90678669]
 [4.00789653 5.02438453 5.62524192 5.22505213 5.44351063 4.58375214]
 [7.83554825 7.42915157 7.08508874 6.2843401  6.74668152 7.34826723]
 [8.88366635 8.86802799 9.23553396 9.02627649 9.30079436 9.20207791]]
```

**Note :** la matrice contient des valeurs aléatoires, avec une distribution uniforme variable pour chaque ligne :<br> $[0,2[$ pour la première ligne, $[2,4[$ pour la seconde ligne, ..., et $[8,10[$ pour la dernière.

In [ ]:
np.random.seed(10) # on force toujours la même séquence aléatoire
j = 'TODO'; show('j#')

---
```
k =
[[0. 1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1. 0. 1. 1.]
 [1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 1. 0.]]
```

In [ ]:
k = 'TODO'; show('k#')

---
```
l =
[[1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3]
 [1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3]
 [1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3]
 [4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6]
 [4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6]
 [4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6]
 [7 7 7 7 7 7 8 8 8 8 8 8 9 9 9 9 9 9]
 [7 7 7 7 7 7 8 8 8 8 8 8 9 9 9 9 9 9]
 [7 7 7 7 7 7 8 8 8 8 8 8 9 9 9 9 9 9]]
```

In [ ]:
l = 'TODO'; show('l#')

<h2 style="padding:16px; color:white; background:#07D">Exercice D2 - Fonctions universelles</h2>

Reprenez les fonctions suivantes, écrites dans les exercices B1, B3 et B5 :

**`gcd_lcm(n)`** ● **`latin(seq)`** ● **`show_maze(maze)`**

et modifiez leur implémentation pour tirer parti des fontionnalités offertes par le package **`numpy`** : utilisation du ***conteneur **`array`** et des fonctions universelles***, afin d'obtenir un code à la fois concis et rapide.


In [ ]:
def gcd_lcm(n):
  """return the GCD/LCM table of size 'n' x 'n', as a 2D numpy array"""
  # TODO

In [ ]:
print(gcd_lcm(9))

In [ ]:
def latin(seq):
  """return a random latin square by shuffling rows and cols of a fixed latin square"""
  # TODO

In [ ]:
show("latin([1,2,3,4,5])#;; latin('ABCDEFGHI')#;; latin({'toto', 'titi', 'tata', 'tutu'})#")

In [ ]:
def show_maze(maze):
  """show maze as a multi-line unicode string"""
  # TODO

In [ ]:
from SRC.tools import load
maze = load('TEST/maze0.txt') # on charge un des labyrinthes à afficher
show_maze(maze)

<h2 style="padding:16px; color:white; background:#07D">Exercice D3 - Manipulation d'images</b></h2>

Une image numérique est définie comme une matrice de pixels où chaque pixel représente une couleur. Il existe trois grandes familles d'images selon la quantité d'information stockée dans chaque pixel :

- Les **images binaires** où chaque pixel ne contient qu'une valeur binaire 0 (= noir) ou 1 (= blanc)
- Les **images monochromes** où chaque pixel contient un scalaire correspondant à l'intensité lumineuse, soit en **`float`** (sur une échelle de 0 à 1), soit en **`int`** (sur une échelle de 0 à 255)
- Les **images polychromes** où chaque pixel contient trois scalaires correspondant à l'intensité des trois couleurs primaires (***RGB*** en synthèse additive, ***CMY*** en synthèse soustractive) avec la même échelle que les images monochromes. Certains formats d'images (PNG, par exemple) utilisent une quatrième composante, appelée *alpha* et notée ***A***, qui permet de stocker une information de transparence

L'objectif de cet exercice est d'utiliser les fonctionnalités du package **`numpy`** pour tester différentes manipulations sur des images qui auront été converties vers un conteneur de type **`array`**. Pour pouvoir charger, sauvegarder et visualiser ces images, nous allons utiliser certaines fonctions fournies par le package **`matplotlib`**. Ce package sera abordé en détail dans le chapitre 6 du cours, mais pour le moment, nous n'aurons besoin que de trois fonctions : **`imread(filename)`** pour charger l'image à partir d'un fichier, **`imshow(image)`** pour l'afficher dans le notebook, et **`imsave(filename, image)`** pour la sauvegarder dans un fichier.

In [ ]:
from matplotlib.pyplot import imread, imsave, imshow, style # import des fonctions
style.use('default') # utilisation du style par défaut pour la visualisation

In [ ]:
tiger = imread('IMG/tiger.jpg') # lecture de l'image sur disque et conversion en 'array'
imshow(tiger) # affichage de l'image avec les paramètres de visualisation par défaut
show("tiger.shape; tiger.dtype") # image polychrome = matrice 3D d'entiers : 480 x 640 x 3

In [ ]:
tigerG = imread('IMG/tigerG.jpg') # lecture de l'image sur disque et conversion en 'array'
imshow(tigerG, cmap='gray') # pour une image monochrome, il faut une palette de couleurs
show("tigerG.shape; tigerG.dtype") # image monochrome = matrice 2D d'entiers : 480 x 640

Une palette de couleur (***colormap***) permet d'associer une couleur à chaque valeur scalaire stockée dans les pixels d'une image monochrome. Le choix s'effectue en spécifiant le nom de la palette choise via le paramètre **`cmap`** de la fonction **`imshow`**. Parmi les palettes prédéfinies de **`matplotlib`**, on peut citer : 

***gray ● jet ● hot ● hsv ● brg ● rainbow ● prism ● flag ● seismic ● viridis ● Blues ● Greens ● Reds ● Purples ● Oranges***

La palette par défaut **`viridis`** a été choisie pour fournir un bon contraste, à la fois lorsqu'on la visualise en couleur sur un écran et lorsqu'on l'imprime sur papier en noir et blanc. Pour chaque palette, il existe une version inversée, obtenue en rajoutant le suffixe **`_r`** au nom de la palette

In [ ]:
# tester l'affichage de l'image 'tigerG.jpg' avec différentes palettes et palettes inversées

In [ ]:
# afficher l'image 'tiger.jpg' en lui faisant subir une symétrie horizontale
# idem avec une symétrie verticale puis une symétrie centrale

In [ ]:
# récupérer la composante R (plan = 0) de 'tiger.jpg' et l'afficher avec la colormap 'Reds_r'
# idem pour la composante G (plan = 1) et G (plan= 2) avec les colormaps 'Greens_r' et 'Blues_r'

In [ ]:
# afficher l'image 'tiger.jpg' en échangeant les composantes R et B

In [ ]:
# afficher l'image 'tiger.jpg' en ne gardant qu'un pixel sur 8 dans les 2 directions (= pixellisation)
# tester également en rajoutant l'argument optionnel : interpolation='bicubic' dans 'imshow'
# différents modes d'interpolation : nearest (= défaut), bilinear, bicubic, gaussian, mitchell, lanczos...

In [ ]:
# diviser l'image 'tigre.jpg' en 4 quadrants : le quadrant NW affiche l'image normale,
# alors que les quadrants NE/SW/SE n'affichent que les composantes R/G/B respectivement

In [ ]:
# charger l'image 'smiley.png' et l'incruster au niveau de l'oeil droit du tigre
# utiliser la composante A du smiley pour sélectionner les pixels à afficher.
# attention : à la différence d'une image JPG, lorsqu'on charge une image PNG, les
# composantes des pixels sont de type 'float' et compris dans l'intervalle [0,1]
# il faut donc effectuer une conversion pour que l'incrustation soit possible

<h2 style="padding:16px; color:white; background:#07D">Exercice D4 - Manipulation de fichiers CSV et NPY</h2>

A suivre...