<p style="color:#FFF; background:#07D; padding:12px; font-size:20px; font-style:italic; text-align:center">
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right">schlick[at]u-bordeaux.fr</span>
<span style="font-size:48px; font-style:normal"><b>EXERCICES EN TEMPS LIMITÉ</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Version 2024-12</span>
<span style="width:49%; display:inline-block; text-align:right">Licence CC-BY-NC-ND</span></p>

- **Nom :**                       ......
- **Prénom :**                    ......
- **Parcours MAS :**              ......
- **Salle CREMI :**               ......
- **Nom du poste :**              ......
- **URL dossier secret CREMI :**  **https://xxx.xxx.emi.u-bordeaux.fr/OI-xxx**
- **URL session ChatGPT :**       **https://chatgpt.com/share/xxx**

<h3 style="padding:16px; color:#FFF; background:#07D">Instructions pour le démarrage du TP</h3>

Avant de démarrer, procéder aux actions suivantes :
- Stockez ce notebook sur votre compte CREMI, dans le même dossier que celui où vous avez placé vos autres notebooks d'exercices, car il va avoir besoin d'accéder à vos dossiers **`SRC`**, **`IMG`** et **`TEST`**

- Commencez par renommer ce notebook sous la forme **nom.prenom.salle.ipynb** en cliquant sur le nom du notebook dans le **File Browser** à gauche et en appuyant sur <kbd>F2</kbd> pour éditer son nom

- Editez la cellule de texte ci-dessus pour remplacer tous les pointillés par les informations vous concernant. Pour l'URL de la session ***ChatGPT***, vous pouvez attendre la fin du TP, lorsque vous aurez créé le lien associé à votre session. Mais il est tout de même conseillé de faire un test de partage de session en début d'épreuve, juste pour vérifier que cela fonctionne correctement sur votre compte

- Exécutez la cellule de code ci-dessous, qui va importer une série de fonctions et de modules qui pourront être utilisés par le code à produire. Il faut noter que tous les imports ne seront pas forcément utiles pour tous les sujets, mais par contre, **aucune autre import ne devra être employé dans le code écrit pour les différents exercices**

In [ ]:
# ------------------------------------------------------------------------------
# ATTENTION : AUCUN AUTRE IMPORT NE SERA AUTORISÉ POUR L'ENSEMBLE DES EXERCICES
# ------------------------------------------------------------------------------
from SRC.tools import load, show
from ipywidgets import interact, interact_manual
import IPython.display as dp
import numpy as np
import matplotlib.pyplot as mp
import pandas as pd
import seaborn as sb
import warnings; warnings.filterwarnings('ignore') # on enlève les 'warning' éventuels

<h3 style="padding:16px; color:#FFF; background:#07D">Informations sur le travail à réaliser</h3>

Ce notebook contient trois exercices de difficulté variable (★ / ★★ / ★★★) qui peuvent être effectués dans un ordre arbitraire. Pour chaque exercice, il s'agit d'écrire le code Python devant répondre au problème proposé. Il faut noter qu'à la différence des exercices faits en TD, il n'y a pas d'indication de type **TODO** détaillant la séquence des opérations à implémenter dans les fonctions, c'est à vous de vous débrouiller de manière autonome pour implémenter l'ensemble des fonctionnalités demandées. Le code à fournir pour la plupart des exercices peut s'inspirer; plus ou moins directement, de portions de code se trouvant dans les exemples du cours ou dans les corrigés des exercices, mais là encore, c'est à vous de trouver, à chaque fois, l'exercice qui pourra vous servir de base.

Comme rappelé en cours, les deux critères qualitatifs principaux qui seront utilisés pour la notation sont :
- le fait de ***produire du code efficace et lisible*** qui utilise des fonctionnalités avancées du langage Python, ainsi que des algorithmes et des structures de données optimisées
- le fait de ***produire du code capable de se fondre dans le style utilisé pour l'UE*** afin d'avoir l'impression d'un développeur unique pour l'ensemble du code

Pour toute la durée de la séance du TP noté, on vous demande également d'ouvrir une session de travail avec votre compte sur <b>ChatGPT</b>. Je vous rappelle les règles strictes concernant cette session de travail :

- Il faut impérativement ***se connecter en début de séance avec votre compte ChatGPT***, sinon vous ne pourrez pas créer, en fin de TP, une URL permettant d'accéder à l'intégralité de votre session
- Il faut impérativement ***utiliser une session non-éphémère***, pour la même raison
- Il faut exclusivement ***utiliser un dialogue en mode texte et sans joindre de fichier***, toujours pour la même raison
- Il faut toujours ***fournir une version alpha du code*** pour les fonctions à écrire, avant de demander l'aide à l'IAG. Cette version alpha ***doit être écrite de manière personnelle***, sans utilisation de l'IAG.
- La version alpha n'a pas besoin d'être fonctionnelle mais elle doit ***définir les différentes variables*** qui vous semblent nécessaires pour votre code et ***donner des indications sur l'algorithme envisagé et/ou sur les fonctions à utiliser***
- La version finale de votre code sera normalement très similaire à la version finale obtenue lors de votre dialogue avec l'IAG. Si vous modifiez significativement le code proposé par l'IAG, il faudra ***rajouter des commentaires dans le code pour expliquer les modifications apportées***
- L'ensemble des dialogues avec l'IAG doit ***toujours s'effectuer en anglais***

<h3 style="padding:16px; color:#FFF; background:#07D">Instructions pour la fin du TP</h3>

A la fin du temps imparti, procéder aux actions suivantes :
- Cliquer sur le bouton **Partager** de votre session ChatGPT pour créer l'URL d'accès pour votre session.
- Copier l'URL obtenue dans la cellule d'entête de ce notebook
- Vérifier que vous avez bien renommé le notebook comme indiqué
- Vérifier que les autres informations demandées dans cette cellule sont bien remplies
- Recopier le notebook dans le dossier habituel de votre espace ***www*** du CREMI
- Envoyer un mail à l'adresse **`mas.outinfo@gmail.com`** avec les informations suivantes :
  * **Titre du message :** le numéro de la salle où vous êtes
  * **Contenu du message :** une copie de la cellule d'entête du notebook
  * **Pièce-jointe au message :** le notebook

<div style="padding:16px; color:#FFF; background:#F64; font-size:12pt">

Pour le TP1, comme il s'agissait de votre premier TP noté avec utilisation de l'IAG, j'ai été incroyablement tolérant envers les étudiants qui n'avaient respecté les consignes que de manière très approximative. Ce ne sera plus le cas pour ce TP2. Donc voici le barème des malus auxquels vous vous exposez en cas du non-respect des instructions ci-dessus :

* Non-respect des modalités du paragraphe "Instructions pour le démarrage du TP" : **-2 points**
* Non-respect des modalités du paragraphe "Informations pour le travail à réaliser" : **-2 points**
* Non-respect des modalités du paragraphe "Instructions pour la fin du TP" : **-2 points**
* Utilisation d'imports de fonctions ou de packages non autorisés : **-2 points par import** 
* Création d'une version alpha par IAG (au travers d'une autre session IAG, en pensant que je ne vais pas le détecter) : **note de 0 pour l'ensemble de l'exercice concerné**
* Absence de partage de la session IAG : **note de 0 pour l'ensemble de l'exercice concerné**
</div>

<h2 style="padding:16px; color:#FFF; background:#07D">G1 - Fonctions génératrices de matrices ★</h2>

On va généraliser le principe mis en oeuvre dans l'exercice **D1**, pour la construction de matrices à l'aide du package **`numpy`**. Au lieu de créer des matrices uniques, on va chercher à écrire des fonctions génératrices de matrices, permettant de contruire toute une famille de matrices basées sur une même structure. Pour chaque fonction génératrice (pour simplifier, on va toutes les appeler **`make`**), on donne un exemple d'exécution qu'il vous faudra ***analyser pour identifier le rôle des paramètres*** dans la construction de la matrice obtenue, et ensuite en déduire un code permettant d'obtenir la même matrice avec le même jeu de paramètres, mais également ***toute la famille des matrices de même structure***, simplement en changeant les valeurs des paramètres. Comme c'était le cas pour l'exercice **D1**, ce code pourra systématiquement se réduire à 2 ou 3 appels de fonctions **numpy**, en piochant dans celles qui ont été utilisées dans le cours ou dans les feuilles de TD.

Il s'agit avant tout d'un exercice de ***prompt engineering*** puisque la difficulté principale consiste à trouver comment décrire, dans votre version alpha du code, la famille de matrices souhaitée pour que l'IAG puisse produire le code adapté pour toutes ces matrices, et pas uniquement pour celle qui est donnée en exemple :

---
```
make(n=6)

[[ 1  2  3  4  5  6  5  4  3  2  1]
 [ 2  4  6  8 10 12 10  8  6  4  2]
 [ 3  6  9 12 15 18 15 12  9  6  3]
 [ 4  8 12 16 20 24 20 16 12  8  4]
 [ 5 10 15 20 25 30 25 20 15 10  5]
 [ 6 12 18 24 30 36 30 24 18 12  6]
 [ 5 10 15 20 25 30 25 20 15 10  5]
 [ 4  8 12 16 20 24 20 16 12  8  4]
 [ 3  6  9 12 15 18 15 12  9  6  3]
 [ 2  4  6  8 10 12 10  8  6  4  2]
 [ 1  2  3  4  5  6  5  4  3  2  1]]

```

In [ ]:
def make(n): # version alpha
  'TODO'

In [ ]:
def make(n): # version finale
  'TODO'

In [ ]:
make(6) # on doit obtenir un résultat équivalent à la matrice exemple

In [ ]:
#make(...) # rajouter un autre exemple avec un autre jeu de paramètres

---
```
make(size=(5,11), seq='ABCDEF')

[['A' 'B' 'C' 'D' 'E' 'F' 'A' 'B' 'C' 'D' 'E']
 ['F' 'A' 'B' 'C' 'D' 'E' 'F' 'A' 'B' 'C' 'D']
 ['E' 'F' 'A' 'B' 'C' 'D' 'E' 'F' 'A' 'B' 'C']
 ['D' 'E' 'F' 'A' 'B' 'C' 'D' 'E' 'F' 'A' 'B']
 ['C' 'D' 'E' 'F' 'A' 'B' 'C' 'D' 'E' 'F' 'A']]
```

In [ ]:
def make(size, seq=(0,1)): # version alpha
  'TODO'

In [ ]:
def make(size, seq=(0,1)): # version finale
  'TODO'

In [ ]:
make((5,11), 'ABCDEF') # on doit obtenir un résultat équivalent à la matrice exemple

In [ ]:
#make(...) # rajouter un autre exemple avec un autre jeu de paramètres

---
```
make(start=1, stop=10, step=2)

[[1 1 1 1 1 1 1 1 1]
 [1 3 3 3 3 3 3 3 1]
 [1 3 5 5 5 5 5 3 1]
 [1 3 5 7 7 7 5 3 1]
 [1 3 5 7 9 7 5 3 1]
 [1 3 5 7 7 7 5 3 1]
 [1 3 5 5 5 5 5 3 1]
 [1 3 3 3 3 3 3 3 1]
 [1 1 1 1 1 1 1 1 1]]

```

In [ ]:
def make(start, stop, step=1): # version alpha
  'TODO'

In [ ]:
def make(start, stop, step=1): # version finale
  'TODO'

In [ ]:
make(1,10,2) # on doit obtenir un résultat équivalent à la matrice exemple

In [ ]:
#make(...) # rajouter un autre exemple avec un autre jeu de paramètres

<h2 style="padding:16px; color:#FFF; background:#07D">G2 - Analyse de la base de données <b><i>Student Performance</i></b> ★★</h2>

La base de données ***Student Performance*** contient diverses informations sur 650 élèves d'un lycée de Boston, couvrant des aspects démographiques, académiques et comportementaux. Voici une description détaillée de chaque colonne présente dans ce jeu de données :

| **Attribut** | **Type** | **Description** |
|--------------|----------|-----------------|
| **sex** | binaire | **Sexe de l'élève** : F = Féminin, M = Masculin |
| **age** | numérique | **Âge de l'élève** : de 15 à 22 ans |
| **residence** | binaire | **Environnement résidentiel** : U = Urbain, R = Rural |
| **parents** | binaire | **Situation des parents** : T = Ensembles, A = Séparés |
| **medu** | numérique | **Niveau d'études de la mère** : 0 = Aucune, 1 = Primaire, 2 = Collège, 3 = Lycée, 4 = Université |
| **fedu** | numérique | **Niveau d'études du père** : idem 'medu' |
| **mjob** | nominal | **Profession de la mère** : teacher/health/services/home/other |
| **fjob** | nominal | **Profession du père** : idem 'mjob' |
| **guardian** | nominal | **Tuteur légal de l'élève** : mother/father/other |
| **famsize** | binaire | **Taille de la famille** : S = Petite (de 1 à 3 personnes), L = Grande (4 ou +) |
| **famrel** | numérique | **Qualité des relations familiales** : 1 = Très mauvais ... 5 = Très bon |
| **asupport** | booléen | **Soutien scolaire académique** : yes/no |
| **fsupport** | booléen | **Soutien scolaire familial** : yes/no |
| **psupport** | booléen | **Soutien scolaire payant** : yes/no |
| **activities** | booléen | **Activités extra-scolaires** : yes/no |
| **sports** | booléen | **Activités sportives** : yes/no |
| **internet** | booléen | **Internet à domicile** : yes/no |
| **romantic** | booléen | **Relation amoureuse** : yes/no |
| **university** | booléen | **Candidature pour l'université** : yes/no |
| **failures** | numérique | **Nombre de redoublements** : de 0 à 4 |
| **traveltime** | numérique | **Durée de transport quotidien** : 1 = 0-15mn, 2 = 15-30mn, 3 = 30-60mn, 4 = > 60mn |
| **studytime** | numérique | **Durée d'étude hebdomadaire** : 1 = 0-2H, 2 = 2-5H, 3 = 5-10H, 4 = > 10H |
| **freetime** | numérique | **Temps libre hebdomadaire** : 1 = Très faible ... 5 = Très élevé |
| **parties** | numérique | **Sorties hebdomadaires** : 1 = Très faible ... 5 = Très élevé |
| **dalcohol** | numérique | **Consommation alcool en semaine** : 1 = Très faible ... 5 = Très élevé |
| **walcohol** | numérique | **Consommation alcool en week-end** : 1 = Très faible ... 5 = Très élevé |
| **health** | numérique | **État de santé** : 1 = Très mauvais ... 5 = Très bon |
| **absences** | numérique | **Nombre de jours d'absence** : de 0 à 100 jours |
| **Q1** | numérique | **Moyenne obtenue au trimestre 1** : de 0 à 20 |
| **Q2** | numérique | **Moyenne obtenue au trimestre 2** : de 0 à 20 |
| **Q3** | numérique | **Moyenne obtenue au trimestre 3** : de 0 à 20 |

La première étape consiste à lire le contenu de la base de données (fichier CSV dont l'URL est fournie ci-dessous) et de le stocker dans une variable **`data`**, sous la forme d'une table **`pandas`**. Pour ne pas fausser les résultats des analyses, il est judicieux de retirer de la table **`data`** tous les élèves n'ayant pas fait l'intégralité de l'année au sein de l'établissement (= ceux qui ont une valeur 0 pour une ou plusieurs des trois colonnes ***Q1, Q2*** ou ***Q3***).

Ensuite, il faut ***écrire les différents codes python permettant de répondre aux 4 questions A/B/C/D*** listées ci-dessous. Pour chaque question, il faudra générer, à l'aide de la bibliothèque **`seaborn`**, la visualisation la mieux adaptée pour présenter les résultats obtenus. A vous de trouver le(s) type(s) de visualisation à mettre en oeuvre pour chaque question, en piochant parmi les exemples vus dans le chapitre 8 et la feuille d'exercices F. N'oubliez pas d'utiliser les propriétés **`hue`** *(permettant de changer la couleur en fonction d'une variable nominale)* et/ou **`size`** *(permettant de changer la taille en fonction d'une variable numérique)*, qui peuvent apporter énormément de lisibilité supplémentaire pour les graphiques...

In [ ]:
url = 'https://www.labri.fr/perso/schlick/outinfo/!!!/students.csv'
data = 'TODO' # récupérer le contenu du fichier CSV et le convertir en table 'pandas' (649 lignes)
data = 'TODO' # conserver uniquement les lignes des étudiants présents aux 3 trimestres (633 lignes)

---
**Question A :** Rajouter une colonne ***M*** correspondant à la moyenne annuelle des notes et visualiser un estimateur de densité pour les 4 distributions ***Q1 / Q2 / Q3 / M***

In [ ]:
# Question A : version alpha
# TODO

In [ ]:
# Question A : version finale
# TODO

---
**Question B :** Combiner les 4 variables binaires ***sex, residence, parents, famsize*** en une variable nominale ***situation*** à 16 valeurs, en concaténant les lettres des 4 variables **`M/F/U/R/T/A/S/L`**. Visualiser les résultats scolaires classées selon ces 16 catégories, en les triant de manière décroissante par rapport à la moyenne des élèves de chaque catégorie

In [ ]:
# Question B : version alpha
# TODO

In [ ]:
# Question B : version finale
# TODO

---
**Question C :** Rajouter une colonne ***involvement*** récapitulant l'implication de l'élève dans ses études, égale à 5x la valeur de ***studytime*** diminuée de la somme des colonnes ***freetime / parties / dalcohol / walcohol***. Existe-t-il une corrélation entre cette colonne ***involvement*** et les résultats scolaires ?

In [ ]:
# Question C : version alpha
# TODO

In [ ]:
# Question C : version finale
# TODO

---
**Question D :** Existe-t-il une relation entre les résultats scolaires et le fait de vouloir candidater à l'Université ?

In [ ]:
# Question D : version alpha
# TODO

In [ ]:
# Question D : version finale
# TODO

<h2 style="padding:16px; color:#FFF; background:#07D">G3 - Distances entre paires de points ★★★</h2>

L'objectif de l'exercice est d'étudier la distribution des distances entre des paires de points générés aléatoirement dans un espace de dimension quelconque, et de vérifier s'il existe des similarités entre ces distributions pour différentes formes et différentes dimensions des espaces considérés.

La première étape consiste à écrire une fonction **`uniform_square(n)`** qui simule un processus stochastique générant des ***positions aléatoires de points, uniformément répartis dans le carré unité centré*** : c'est-à-dire que les coordonnées $(x,y)$ des points générés doivent vérifier $(x,y) \in [-1,1]^2$. La fonction doit renvoyer une matrice **numpy** de taille $n \times 2$ stockant les coordonnées $x$ et $y$ des $n$ points aléatoires générés.

In [ ]:
def uniform_square(n): # version alpha
  """return matrix of coords of 'n' random points with uniform distribution in unit centered square"""

In [ ]:
def uniform_square(n): # version finale
  """return matrix of coords of 'n' random points with uniform distribution in unit centered square"""

In [ ]:
square_samples = uniform_square(10000) # on génère 10000 échantillons

Pour vérifier que la répartition des points est bien uniforme sur l'ensemble du carré, écrire une fonction **`show_positions(samples)`** qui génère un graphique affichant les positions des points 2D stockés dans **`samples`**. A vous de trouver, parmi les fonctions de **matplotlib** ou de **seaborn**, la meilleure manière d'obtenir ce résultat visuel (on doit afficher les points et vérifier visuellement que la densité des points est bien homogène sur l'ensemble du carré unité) :

In [ ]:
def show_positions(samples): # version alpha
  """show positions of provided 'samples', where all of them are located in the unit centered square"""

In [ ]:
def show_positions(samples): # version finale
  """show positions of provided 'samples', where all of them are located in the unit centered square"""

In [ ]:
show_positions(square_samples) # on teste avec les échantillons du carré unité

Enfin, il ne reste plus qu'à écrire une fonction **`show_distances(samples)`** qui calcule les distances entre les paires de points stockés dans **`samples`** et affiche l'histogramme, ainsi qu'une estimateur de densité, pour la distribution obtenue. Les paires de points à prendre en compte pour les calculs sont tout simplement deux points successifs de la matrice **`samples`** (on rajoutera la distance entre le dernier et le premier point, pour avoir autant de distances que de points). Pour préserver l'efficacité de **numpy** il est primordial que cette fonction n'utilise pas de boucle **`for`** ou **`while`** :

In [ ]:
def show_distances(samples): # version alpha
  """show distribution of distances between pairs of points in provided 'samples'"""

In [ ]:
def show_distances(samples): # version finale
  """show distribution of distances between pairs of points in provided 'samples'"""

In [ ]:
show_distances(square_samples) # on teste avec les échantillons du carré unité

---
La seconde étape consiste à écrire une fonction **`uniform_circle(n)`** qui simule un processus stochastique générant des ***positions aléatoires de points, uniformément répartis dans le cercle unité centré*** : c'est-à-dire que les coordonnées $(x,y)$ des points générés doivent vérifier $x^2 + y^2 \in [0,1]$. Comme la précédente, la fonction doit renvoyer une matrice **numpy** de taille $n \times 2$ stockant les coordonnées $x$ et $y$ des $n$ points aléatoires générés. Attention, il faut que la répartition des points dans le cercle soit uniforme, ce qui est un peu plus compliqué à obtenir que pour le carré.

In [ ]:
def uniform_circle(n): # version alpha
  """return matrix of coords of 'n' random points with uniform distribution in unit centered circle"""

In [ ]:
def uniform_circle(n): # version finale
  """return matrix of coords of 'n' random points with uniform distribution in unit centered circle"""

In [ ]:
circle_samples = uniform_circle(10000) # on génère 10000 échantillons

Comme les échantillons du cercle unité sont inclus dans le carré unité, la fonction **`show_positions`** écrite plus haut, peut être utilisée sans modification pour vérifier si la répartition des points générés est bien uniforme dans le cercle unité :

In [ ]:
show_positions(circle_samples) # on teste avec les échantillons du cercle unité

De la même manière, la fonction **`show_distances`** précédente, devrait fonctionner sans difficulté sur les échantillons stockés dans **`circle_samples`** :

In [ ]:
show_distances(circle_samples) # on teste avec les échantillons du cercle unité

En se basant sur ce qui a été fait dans l'exercice E1, modifier la fonction **`show_distances`** pour qu'elle prenne en paramètre, un dictionnaire contenant plusieurs distributions, chacune associée à une clé contenant son nom. La fonction doit ainsi permettre d'afficher plusieurs distributions sur le même graphique, permettant une comparaison plus facile :

In [ ]:
def show_distances(groups): # version alpha
  """show distribution of distances between pairs of points, for all sample groups"""

In [ ]:
def show_distances(groups): # version finale
  """show distribution of distances between pairs of points, for all sample groups"""

In [ ]:
groups = dict(square=square_samples, circle=circle_samples) # on crée le dictionnaire des échantillons
show_distances(groups) # on affiche sur la même figure, toutes les distributions stockées dans 'groups'

---
On souhaite maintenant généraliser ce résultat à une dimension quelconque : au lieu d'un carré, les échantillons vont être ***générés uniformément dans un hypercube de dimension $d$***, et au lieu d'un cercle, les échantillons vont être ***générés uniformément dans une hypersphère de dimension $d$***. En se basant sur les fonctions précédentes, écrire les deux fonctions **`uniform_hypercube(n, d=2)`** et **`uniform_hypersphere(n, d=2)`** qui doivent retourner une matrice $n \times d$ contenant les échantillons demandés pour l'espace de dimension $d$ :

In [ ]:
def uniform_hypercube(n, d=2): # version alpha
  """return matrix of coords of 'n' uniform random points in unit centered hypercube of dimension 'd'"""

In [ ]:
def uniform_hypercube(n, d=2): # version finale
  """return matrix of coords of 'n' uniform random points in unit centered hypercube of dimension 'd'"""

In [ ]:
def uniform_hypersphere(n, d=2): # version alpha
  """return matrix of coords of 'n' uniform random points in unit centered hypersphere of dimension 'd'"""

In [ ]:
def uniform_hypersphere(n, d=2): # version finale
  """return matrix of coords of 'n' uniform random points in unit centered hypersphere of dimension 'd'"""

Normalement, si elle a été bien écrite, la fonction **`show_distances(groups)`** devrait pouvoir générer naturellement des calculs de distance en dimension quelconque. Donc vous devriez pouvoir l'utiliser directement, sinon vous pouvez la modifier légèrement pour qu'elle accepte des points d'un espace de dimension arbitraire :

In [ ]:
cube_samples = uniform_hypercube(10000, 3) # on génère 10000 échantillons dans un cube (d=3)
sphere_samples = uniform_hypersphere(10000, 3) # on génère 10000 échantillons dans une sphere (d=3)
groups['cube'], groups['sphere'] = cube_samples, sphere_samples # on rajoute les nouveaux échantillons
show_distances(groups) # et on affiche les 4 distributions sur la même figure

<h2 style="padding:0 0 8px; margin:0 -20px; color:#FFF; background:#07D; text-align:right">● ● ●</h3>