<p style="color:#FFF; background:#07D; padding:12px; font-size:20px; font-style:italic; text-align:center">
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right">schlick[at]u-bordeaux.fr</span>
<span style="font-size:48px; font-style:normal"><b>EXERCICES EN TEMPS LIMITÉ</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Version 2024-12</span>
<span style="width:49%; display:inline-block; text-align:right">Licence CC-BY-NC-ND</span></p>

- **Nom :**                       ......
- **Prénom :**                    ......
- **Parcours MAS :**              ......
- **Salle CREMI :**               ......
- **Nom du poste :**              ......
- **URL dossier secret CREMI :**  https://xxx-xxx.emi.u-bordeaux.fr/OI-xxx
- **URL session ChatGPT :**       https://chatgpt.com/share/xxx

<h3 style="padding:16px; color:#FFF; background:#07D">Instructions pour le démarrage du TP</h3>

Avant de démarrer, procéder aux actions suivantes :
- Stockez ce notebook sur votre compte CREMI, dans le même dossier que celui où vous avez placé vos autres notebooks d'exercices, car il va avoir besoin d'accéder à vos dossiers **`SRC`**, **`IMG`** et **`TEST`**

- Commencez par renommer ce notebook sous la forme **nom.prenom.salle.ipynb** en cliquant sur le nom du notebook dans le **File Browser** à gauche et en appuyant sur <kbd>F2</kbd> pour éditer son nom

- Editez la cellule de texte ci-dessus pour remplacer tous les pointillés par les informations vous concernant. Pour l'URL de la session ***ChatGPT***, vous pouvez attendre la fin du TP, lorsque vous aurez créé le lien associé à votre session. Mais il est tout de même conseillé de faire un test de partage de session en début d'épreuve, juste pour vérifier que cela fonctionne correctement sur votre compte

- Exécutez la cellule de code ci-dessous, qui va importer une série de fonctions et de modules qui pourront être utilisés par le code à produire. Il faut noter que tous les imports ne seront pas forcément utiles pour tous les sujets, mais par contre, **aucune autre import ne devra être employé dans le code écrit pour les différents exercices**

In [ ]:
# ------------------------------------------------------------------------------
# ATTENTION : AUCUN AUTRE IMPORT NE SERA AUTORISÉ POUR L'ENSEMBLE DES EXERCICES
# ------------------------------------------------------------------------------
from SRC.tools import load, show
from ipywidgets import interact, interact_manual
import IPython.display as dp
import numpy as np
import matplotlib.pyplot as mp
import pandas as pd
import seaborn as sb
import warnings; warnings.filterwarnings('ignore') # on enlève les 'warning' éventuels

<h3 style="padding:16px; color:#FFF; background:#07D">Informations sur le travail à réaliser</h3>

Ce notebook contient trois exercices de difficulté variable (★ / ★★ / ★★★) qui peuvent être effectués dans un ordre arbitraire. Pour chaque exercice, il s'agit d'écrire le code Python devant répondre au problème proposé. Il faut noter qu'à la différence des exercices faits en TD, il n'y a pas d'indication de type **TODO** détaillant la séquence des opérations à implémenter dans les fonctions, c'est à vous de vous débrouiller de manière autonome pour implémenter l'ensemble des fonctionnalités demandées. Le code à fournir pour la plupart des exercices peut s'inspirer; plus ou moins directement, de portions de code se trouvant dans les exemples du cours ou dans les corrigés des exercices, mais là encore, c'est à vous de trouver, à chaque fois, l'exercice qui pourra vous servir de base.

Comme rappelé en cours, les deux critères qualitatifs principaux qui seront utilisés pour la notation sont :
- le fait de ***produire du code efficace et lisible*** qui utilise des fonctionnalités avancées du langage Python, ainsi que des algorithmes et des structures de données optimisées
- le fait de ***produire du code capable de se fondre dans le style utilisé pour l'UE*** afin d'avoir l'impression d'un développeur unique pour l'ensemble du code

Pour toute la durée de la séance du TP noté, on vous demande également d'ouvrir une session de travail avec votre compte sur <b>ChatGPT</b>. Je vous rappelle les règles strictes concernant cette session de travail :

- Il faut impérativement ***se connecter en début de séance avec votre compte ChatGPT***, sinon vous ne pourrez pas créer, en fin de TP, une URL permettant d'accéder à l'intégralité de votre session
- Il faut impérativement ***utiliser une session non-éphémère***, pour la même raison
- Il faut exclusivement ***utiliser un dialogue en mode texte et sans joindre de fichier***, toujours pour la même raison
- Il faut toujours ***fournir une version alpha du code*** pour les fonctions à écrire, avant de demander l'aide à l'IAG. Cette version alpha ***doit être écrite de manière personnelle***, sans utilisation de l'IAG.
- La version alpha n'a pas besoin d'être fonctionnelle mais elle doit ***définir les différentes variables*** qui vous semblent nécessaires pour votre code et ***donner des indications sur l'algorithme envisagé et/ou sur les fonctions à utiliser***
- La version finale de votre code sera normalement très similaire à la version finale obtenue lors de votre dialogue avec l'IAG. Si vous modifiez significativement le code proposé par l'IAG, il faudra ***rajouter des commentaires dans le code pour expliquer les modifications apportées***
- L'ensemble des dialogues avec l'IAG doit ***toujours s'effectuer en anglais***

<h3 style="padding:16px; color:#FFF; background:#07D">Instructions pour la fin du TP</h3>

A la fin du temps imparti, procéder aux actions suivantes :
- Cliquer sur le bouton **Partager** de votre session ChatGPT pour créer l'URL d'accès pour votre session.
- Copier l'URL obtenue dans la cellule d'entête de ce notebook
- Vérifier que vous avez bien renommé le notebook comme indiqué
- Vérifier que les autres informations demandées dans cette cellule sont bien remplies
- Recopier le notebook dans le dossier habituel de votre espace ***www*** du CREMI
- Envoyer un mail à l'adresse **`outinfo@gmx.fr`** avec les informations suivantes :
  * **Titre du message :** le numéro de la salle où vous êtes
  * **Contenu du message :** une copie de la cellule d'entête du notebook
  * **Pièce-jointe au message :** le notebook

<div style="padding:16px; color:#FFF; background:#F64; font-size:12pt">

<center><h4>Barème des malus appliqués en cas du non-respect des instructions ci-dessus</h4></center>

* Non-respect des modalités du paragraphe "Instructions pour le démarrage du TP" : **-2 points**
* Non-respect des modalités du paragraphe "Informations pour le travail à réaliser" : **-2 points**
* Non-respect des modalités du paragraphe "Instructions pour la fin du TP" : **-2 points**
* Utilisation d'imports de fonctions ou de packages non autorisés : **-2 points par import** 
* Création d'une version alpha par IAG (au travers d'une autre session IAG, en pensant que je ne vais pas le détecter) : **note de 0 pour l'ensemble de l'exercice concerné**
* Absence de partage de la session IAG : **note de 0 pour l'ensemble de l'exercice concerné**
</div>

<h2 style="padding:16px; color:#FFF; background:#07D">H1 - Fonctions génératrices de matrices ★</h2>

On va généraliser le principe mis en oeuvre dans l'exercice **D1**, pour la construction de matrices à l'aide du package **`numpy`**. Au lieu de créer des matrices uniques, on va chercher à écrire des fonctions génératrices de matrices, permettant de contruire toute une famille de matrices basées sur une même structure. Pour chaque fonction génératrice (pour simplifier, on va toutes les appeler **`make`**), on donne un exemple d'exécution qu'il vous faudra ***analyser pour identifier le rôle des paramètres*** dans la construction de la matrice obtenue, et ensuite en déduire un code permettant d'obtenir la même matrice avec le même jeu de paramètres, mais également ***toute la famille des matrices de même structure***, simplement en changeant les valeurs des paramètres. Comme c'était le cas pour l'exercice **D1**, ce code pourra systématiquement se réduire à 2 ou 3 appels de fonctions **numpy**, en piochant dans celles qui ont été utilisées dans le cours ou dans les feuilles de TD.

Il s'agit avant tout d'un exercice de ***prompt engineering*** puisque la difficulté principale consiste à trouver comment décrire, dans votre version alpha du code, la famille de matrices souhaitée pour que l'IAG puisse produire le code adapté pour toutes ces matrices, et pas uniquement pour celle qui est donnée en exemple :

---
```
make(size=(11,14), center=-1, corner=0)

[[ 0  0  0  0  0 -1 -1 -1 -1  0  0  0  0  0]
 [ 0  0  0  0 -1 -1 -1 -1 -1 -1  0  0  0  0]
 [ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0]
 [ 0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0]
 [ 0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [ 0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0]
 [ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0]
 [ 0  0  0  0 -1 -1 -1 -1 -1 -1  0  0  0  0]
 [ 0  0  0  0  0 -1 -1 -1 -1  0  0  0  0  0]]

```

In [ ]:
def make(size, center, corner): # version alpha
  'TODO'

In [ ]:
def make(size, center, corner): # version finale
  'TODO'

In [ ]:
make((11,14), -1, 0)  # on doit obtenir un résultat équivalent à la matrice exemple

In [ ]:
#make(...) # rajouter un autre exemple avec un autre jeu de paramètres

---
```
make(seq='ABCDEFGH', repeat=5)

[['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']
 ['H' 'G' 'F' 'E' 'D' 'C' 'B' 'A']
 ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']
 ['H' 'G' 'F' 'E' 'D' 'C' 'B' 'A']
 ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']]
```

In [ ]:
def make(seq, repeat=1): # version alpha
  'TODO'

In [ ]:
def make(seq, repeat=1): # version finale
  'TODO'

In [ ]:
make('ABCDEFGH', 5) # on doit obtenir un résultat équivalent à la matrice exemple

In [ ]:
#make(...) # rajouter un autre exemple avec un autre jeu de paramètres

---
```
make(size=(10,15))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 11 10  9]
 [ 1  2  3  4  5  6  7  8  9 10 11 11 10  9  8]
 [ 2  3  4  5  6  7  8  9 10 11 11 10  9  8  7]
 [ 3  4  5  6  7  8  9 10 11 11 10  9  8  7  6]
 [ 4  5  6  7  8  9 10 11 11 10  9  8  7  6  5]
 [ 5  6  7  8  9 10 11 11 10  9  8  7  6  5  4]
 [ 6  7  8  9 10 11 11 10  9  8  7  6  5  4  3]
 [ 7  8  9 10 11 11 10  9  8  7  6  5  4  3  2]
 [ 8  9 10 11 11 10  9  8  7  6  5  4  3  2  1]
 [ 9 10 11 11 10  9  8  7  6  5  4  3  2  1  0]]
```

In [ ]:
def make(size): # version alpha
  'TODO'

In [ ]:
def make(size): # version finale
  'TODO'

In [ ]:
make((10,15)) # on doit obtenir un résultat équivalent à la matrice exemple

In [ ]:
#make(...) # rajouter un autre exemple avec un autre jeu de paramètres

<h2 style="padding:16px; color:#FFF; background:#07D">H2 - Analyse de la base de données <b><i>Student Performance</i></b> ★★</h2>

La base de données ***Student Performance*** contient diverses informations sur 650 élèves d'un lycée de Boston, couvrant des aspects démographiques, académiques et comportementaux. Voici une description détaillée de chaque colonne présente dans ce jeu de données :

| **Attribut** | **Type** | **Description** |
|--------------|----------|-----------------|
| **sex** | binaire | **Sexe de l'élève** : F = Féminin, M = Masculin |
| **age** | numérique | **Âge de l'élève** : de 15 à 22 ans |
| **residence** | binaire | **Environnement résidentiel** : U = Urbain, R = Rural |
| **parents** | binaire | **Situation des parents** : T = Ensembles, A = Séparés |
| **medu** | numérique | **Niveau d'études de la mère** : 0 = Aucune, 1 = Primaire, 2 = Collège, 3 = Lycée, 4 = Université |
| **fedu** | numérique | **Niveau d'études du père** : idem 'medu' |
| **mjob** | nominal | **Profession de la mère** : teacher/health/services/home/other |
| **fjob** | nominal | **Profession du père** : idem 'mjob' |
| **guardian** | nominal | **Tuteur légal de l'élève** : mother/father/other |
| **famsize** | binaire | **Taille de la famille** : S = Petite (de 1 à 3 personnes), L = Grande (4 ou +) |
| **famrel** | numérique | **Qualité des relations familiales** : 1 = Très mauvais ... 5 = Très bon |
| **asupport** | booléen | **Soutien scolaire académique** : yes/no |
| **fsupport** | booléen | **Soutien scolaire familial** : yes/no |
| **psupport** | booléen | **Soutien scolaire payant** : yes/no |
| **activities** | booléen | **Activités extra-scolaires** : yes/no |
| **sports** | booléen | **Activités sportives** : yes/no |
| **internet** | booléen | **Internet à domicile** : yes/no |
| **romantic** | booléen | **Relation amoureuse** : yes/no |
| **university** | booléen | **Candidature pour l'université** : yes/no |
| **failures** | numérique | **Nombre de redoublements** : de 0 à 4 |
| **traveltime** | numérique | **Durée de transport quotidien** : 1 = 0-15mn, 2 = 15-30mn, 3 = 30-60mn, 4 = > 60mn |
| **studytime** | numérique | **Durée d'étude hebdomadaire** : 1 = 0-2H, 2 = 2-5H, 3 = 5-10H, 4 = > 10H |
| **freetime** | numérique | **Temps libre hebdomadaire** : 1 = Très faible ... 5 = Très élevé |
| **parties** | numérique | **Sorties hebdomadaires** : 1 = Très faible ... 5 = Très élevé |
| **dalcohol** | numérique | **Consommation alcool en semaine** : 1 = Très faible ... 5 = Très élevé |
| **walcohol** | numérique | **Consommation alcool en week-end** : 1 = Très faible ... 5 = Très élevé |
| **health** | numérique | **État de santé** : 1 = Très mauvais ... 5 = Très bon |
| **absences** | numérique | **Nombre de jours d'absence** : de 0 à 100 jours |
| **Q1** | numérique | **Moyenne obtenue au trimestre 1** : de 0 à 20 |
| **Q2** | numérique | **Moyenne obtenue au trimestre 2** : de 0 à 20 |
| **Q3** | numérique | **Moyenne obtenue au trimestre 3** : de 0 à 20 |

La première étape consiste à lire le contenu de la base de données (fichier CSV dont l'URL est fournie ci-dessous) et de le stocker dans une variable **`data`**, sous la forme d'une table **`pandas`**. Pour ne pas fausser les résultats des analyses, il est judicieux de retirer de la table **`data`** tous les élèves n'ayant pas fait l'intégralité de l'année au sein de l'établissement (= ceux qui ont une valeur 0 pour une ou plusieurs des trois colonnes ***Q1, Q2*** ou ***Q3***).

Ensuite, il faut ***écrire les différents codes python permettant de répondre aux 4 questions A/B/C/D*** listées ci-dessous. Pour chaque question, il faudra générer, à l'aide de la bibliothèque **`seaborn`**, la visualisation la mieux adaptée pour présenter les résultats obtenus. A vous de trouver le(s) type(s) de visualisation à mettre en oeuvre pour chaque question, en piochant parmi les exemples vus dans le chapitre 8 et la feuille d'exercices F. N'oubliez pas d'utiliser les propriétés **`hue`** *(permettant de changer la couleur en fonction d'une variable nominale)* et/ou **`size`** *(permettant de changer la taille en fonction d'une variable numérique)*, qui peuvent apporter énormément de lisibilité supplémentaire pour les graphiques...

In [ ]:
url = 'https://www.labri.fr/perso/schlick/outinfo/!!!/students.csv'
data = 'TODO' # récupérer le contenu du fichier CSV et le convertir en table 'pandas' (649 lignes)
data = 'TODO' # conserver uniquement les lignes des étudiants présents aux 3 trimestres (633 lignes)

---
**Question A :** Rajouter une colonne ***M*** correspondant à la moyenne annuelle des notes et visualiser un estimateur de densité pour les 3 distributions ***Q1-M / Q2-M / Q3-M***. Que peut-on en déduire pour les résultats entre ***Q1 / Q2 / Q3*** ?

In [ ]:
# Question A : version alpha
# TODO

In [ ]:
# Question A : version finale
# TODO

---
**Question B :** Entre les 8 variables binaires ou booléennes ***sex, residence, parents, famsize, activities, sports, internet, romantic***, quelle est celle qui a le plus d'influence sur les résultats scolaires ?

In [ ]:
# Question B : version alpha
# TODO

In [ ]:
# Question B : version finale
# TODO

---
**Question C :** Combiner les 3 variables booléennes ***asupport, fsupport, psupport*** en une variable nominale ***support*** à 8 valeurs possibles : **`N/A/F/AF/P/AP/FP/AFP`** selon les cours de soutien scolaire suivis par les étudiants, de **`N`** (élève sans aucun soutien) à **`AFP`** (élève combinant les 3 types de soutiens). Visualiser les résultats scolaires classés selon ces 8 catégories, en les triant de manière décroissante par rapport à la moyenne des élèves de chaque catégorie

In [ ]:
# Question C : version alpha
# TODO

In [ ]:
# Question C : version finale
# TODO

---
**Question D :** Existe-t-il une relation entre l'état de santé et le nombre de jours d'absence ?

In [ ]:
# Question D : version alpha
# TODO

In [ ]:
# Question D : version finale
# TODO

<h2 style="padding:16px; color:#FFF; background:#07D">H3 - Dynamique des populations ★★★</h2>

L'objectif de l'exercice est d'étudier le [**modèle proie-prédateur**](https://fr.wikipedia.org/wiki/%C3%89quations_de_pr%C3%A9dation_de_Lotka-Volterra), formulé indépendamment par Alfred Lotka en 1925 et Vito Volterra en 1926. Il s'agit d'un système d'équations différentielles décrivant la ***dynamique des populations de deux espèces animales*** $x$ et $y$, en fonction de quatre paramètres $(\alpha,\beta,\delta,\gamma)$ qui doivent impérativement être strictement positifs :
$$
\frac{dx}{dt} = \alpha\, x - \beta\, x\, y \qquad\qquad \frac{dy}{dt} = \delta\, x\, y - \gamma\, y
$$

- $x$ : **population des proies** à l'instant $t$
- $y$ : **population des prédateurs** à l'instant $t$
- $\alpha$ : **taux de croissance des proies** (en l'absence de prédateurs)
- $\beta$ : **taux de prédation** (probabilité qu'un prédateur rencontre une proie et la consomme)
- $\delta$ : **taux de croissance des prédateurs** (en fonction de la consommation des proies)
- $\gamma$ : **taux de mortalité des prédateurs** (en l'absence de proies)

En partant d'une population initiale de proies $x_0$ et de prédateurs $y_0$, le modèle permet ainsi de calculer l'évolution combinée des deux populations $x(t)$ et $y(t)$ en fonction du temps. Il s'agit d'un modèle simplifié de dynamique des populations, qui repose sur les trois hypothèses suivantes :

1. La population des proies croît de manière exponentielle en l'absence de prédateurs
1. La population des prédateurs dépend uniquement du nombre de proies disponibles
1. L'interaction entre les deux espèces est le seul facteur contrôlant les taux de natalité et de mortalité

La figure ci-dessous représente l'évolution du modèle avec les paramètres suivants :

$$
x_0 = 10\qquad y_0 = 2\qquad \alpha = 1\qquad \beta = 0.1\qquad \delta = 0.1\qquad \gamma = 1
$$
![lovo.png](https://www.labri.fr/perso/schlick/outinfo/!!!/lovo.png)

La figure à gauche représente ***l'évolution temporelle*** des deux populations $x(t)$ et $y(t)$, et la figure de droite représente ***le diagramme de phase***, c'est-à-dire la relation quantitative entre les deux populations. Comme on peut le constater, le modèle génère des oscillations périodiques des populations de proies et de prédateurs : quand les proies sont abondantes, les prédateurs prospèrent, ce qui va réduire la population des proies, mais quand la population de proies a trop diminué, la population de prédateurs diminue également par manque de nourriture, et lorsque les prédateurs déclinent, les proies peuvent à nouveau prospérer, relançant le cycle. Avec le jeu de paramètres choisi, les courbes d'évolution sont parfaitement symétriques (ce n'est pas le cas avec d'autres jeux de paramètres) : l'augmentation de la population des proies est exactement symétrique à celle du déclin des prédateurs, et inversement, le déclin des proies est symétrique avec celle de l'augmentation de la population des prédateurs. Il faut noter que ***le déclin des prédateurs est toujours plus lent que celui des proies***, résultat qui est vérifié pour tous les jeux de paramètres $(\alpha, \beta, \delta, \gamma)$. Enfin dernier point, on montrer de manière théorique que dans le diagramme de phase, ***les populations vont toujours effectuer un cycle autour d'un point d'équilibre*** défini par $x^* = \gamma / \delta$ et $y^* = \alpha / \beta$ et qui est visualisé en rouge sur la figure de droite.

---
Pour simuler numériquement le modèle de Lockta/Volterra, on va utiliser la [**méthode d'Euler**](https://fr.wikipedia.org/wiki/M%C3%A9thode_d%27Euler) dont le principe est d'effectuer une discrétisation de l'axe temporel pour transformer les deux évolutions $x(t)$ et $y(t)$ en deux séries chronologiques :

$$
x_{n+1} = x_n + \Delta t\,(\alpha\, x_n - \beta\, x_n\, y_n)\qquad\qquad
y_{n+1} = y_n + \Delta t\,(\delta\, x_n\,y_n - \gamma\, y_n)
$$

Autrement dit, on va calculer les termes $x_n$ et $y_n$ de manière incrémentale, en partant des conditions initiales $x_0$ et $y_0$ qui elles sont connues. A partir de ces explications, écrire une fonction **`lovo_euler(x0, y0, args, time, n)`** qui va mettre en oeuvre la méthode d'Euler pour le modèle de Lockta/Volterra et renvoyer trois vecteurs **`t`**, **`x`** et **`y`** de taille **`n`**, contenant respectivement la séquence des pas temporels $t_n$ et les termes des deux séries chronologiques $x_n$ et $y_n$. Les paramètres **`x0`** et **`y0`** correspondent aux conditions initiales, **`args`** est un tuple contenant les valeurs des 4 paramètres $(\alpha, \beta, \delta, \gamma)$, **`time`** correspond à la borne supérieure de la fenêtre temporelle utilisée par la simulation (sachant que la borne inférieure est toujours égale à 0), et enfin **`n`** représente le nombre de pas incrémentaux à effectuer par l'algorithme.

Il faut noter qu'on ne pourra pas utiliser ici les techniques de vectorisation de **numpy** pour calculer les termes de la série en une seule opération, puisque le calcul de chaque nouveau terme nécessite de connaitre le terme précédent. Ce qui signifie que la fonction **`lovo_euler`** devra nécessairement utiliser une boucle **`for`** pour effectuer les calculs :

In [ ]:
def lovo_euler(x0, y0, args, time, n): # version alpha
  """use Euler method to compute the evolution of the Lockta-Volterra prey-predator model"""
  t, x, y = np.zeros(n), np.zeros(n), np.zeros(n)
  # TODO
  return t, x, y # return vectors containing time samples, prey population and predator population

In [ ]:
def lovo_euler(x0, y0, args, time, n): # version finale
  """use Euler method to compute the evolution of the Lockta-Volterra prey-predator model"""
  t, x, y = np.zeros(n), np.zeros(n), np.zeros(n)
  # TODO
  return t, x, y # return vectors containing time samples, prey population and predator population

Pour valider l'implémentation, on va tester la fonction sur le jeu de paramètres utilisé pour la figure de référence, ci-dessus :

In [ ]:
x0, y0, args = 10, 2, (1.0, 0.1, 0.1, 1.0) # on utilise le jeu de paramètres de la figure de référence
t, x, y = lovo_euler(x0, y0, args, 20, 2000) # on utilise 2000 pas pour une fenêtre temporelle de 20 unités
show("min(x); max(x); min(y); max(y)") # on obtient 1.6268733 30.6209140 1.7325381 30.8876090 (ou pas loin)

---
Pour vérifier l'implémentation de manière plus précise, écrire une fonction **`show_lovo(t, x, y, args)`** qui permet de recréer les 2 graphiques **matplotlib** utilisées dans la figure de référence (l'évolution temporelle doit utiliser deux tiers de la largeur du notebook, le tiers restant étant pour le diagramme de phase). Les paramètres **`t`**, **`x`** et **`y`** sont des vecteurs **numpy** contenant les valeurs d'échantillonnage pour la fenêtre temporelle, la population des proies et la population des prédateurs, le paramètre **`args`** a le même rôle que ci-dessus, et ne sera utilisé que pour calculer et afficher le point d'équilibre du modèle dans le diagramme de phase :

In [ ]:
def show_lovo(t, x, y, args): # version alpha
  """plot temporal and phase diagrams for provided time series 'x' and 'y' of the Lotcka/Volterra model"""
  # TODO

In [ ]:
def show_lovo(t, x, y, args): # version finale
  """plot temporal and phase diagrams for provided time series 'x' and 'y' of the Lotcka/Volterra model"""
  # TODO

In [ ]:
show_lovo(t, x, y, args) # on obtient une figure pas tout à fait équivalente à la figure de référence

La figure générée par votre fonction **`show_lovo`** ne sera pas parfaitement identique à la figure de référence : par exemple, les trois oscillations des courbes $x(t)$ et $y(t)$ dans l'évolution temporelle n'ont pas exactement la même hauteur, et le diagramme de phase ne montre pas une courbe cyclique, mais une courbe qui dérive à chaque période. Ce résultat est dû à l'imprécision de la méthode d'Euler avec les paramètres utilisés. Pour corriger cela, il y a deux options possibles :

- soit on augmente de manière importante le nombre $n$ de pas incrémentaux utilisés par la méthode d'Euler ***(pour obtenir une visualisation similaire à la figure de référence, il faut passer à $n = 50000$)*** ce qui va évidemment augmenter très fortement, à la fois le temps de calcul et l'espace mémoire nécessaire

- soit on utilise un solveur alternatif donnant de meilleurs résultats. C'est ce qu'on va faire ici en implémentant la [**méthode de Runge-Kutta**](https://fr.wikipedia.org/wiki/M%C3%A9thodes_de_Runge-Kutta) qui donne des résultats beaucoup plus précis avec beaucoup moins de pas incrémentaux

Ecrire une fonction **`lovo_rk4(x0, y0, args, time, n)`** qui a le même rôle et les mêmes paramètres que la fonction **`lovo_euler`**, mais qui effectue la simulation avec la méthode Runge/Kutta d'order 4. Si vous n'avez jamais entendu parler de cette méthode, ce n'est pas grave, car en rédigeant correctement le prompt liée à la version alpha, l'IAG devrait retourner sans difficulté un code correct et optimisé :

In [ ]:
def lovo_rk4(x0, y0, args, time, n): # version alpha
  """use Runge/Kutta method (order 4) to compute the evolution of the Lockta-Volterra prey-predator model"""
  t, x, y = np.zeros(n), np.zeros(n), np.zeros(n)
  # TODO
  return t, x, y # return vectors containing time samples, prey population and predator population

In [ ]:
def lovo_rk4(x0, y0, args, time, n): # version finale
  """use Runge/Kutta method (order 4) to compute the evolution of the Lockta-Volterra prey-predator model"""
  t, x, y = np.zeros(n), np.zeros(n), np.zeros(n)
  # TODO
  return t, x, y # return vectors containing time samples, prey population and predator population

Si la fonction est bien implémentée, vous devriez obtenir une figure identique à la figure de référence, en utilisant uniquement 200 pas incrémentaux, soit ***250x moins que ceux qui étaient nécessaires avec la méthode d'Euler*** :

In [ ]:
x0, y0, args = 10, 2, (1.0, 0.1, 0.1, 1.0) # on utilise le jeu de paramètres de la figure de référence
t, x, y = lovo_rk4(x0, y0, args, 20, 200) # on utilise 200 pas pour une fenêtre temporelle de 20 unités
show_lovo(t, x, y, args) # on obtient une figure parfaitement équivalente à la figure de référence

---
En gardant les conditions initiales $(x_0, y_0) = (10, 2)$, on souhaite obtenir le jeu de paramètres $(\alpha, \beta, \delta, \gamma)$ qui engendre le système le plus stable, c'est-à-dire que ***la somme des variances des séries $x_n$ et $y_n$ soit minimale***.

Ecrire une fonction **`most_stable(x0, y0, args, time, n)`** qui retourne le tuple $(\alpha, \beta, \delta, \gamma)$ donnant ce système de variance minimale. La fonction possède les mêmes noms de paramètres que les fonctions **`lovo_euler`** et **`lovo_rk4`**, mais le paramètre **`args`** a une forme différente : il va définir le domaine de recherche des 4 paramètres sous la forme d'un tuple de 8 valeurs $(\alpha_{min},\alpha_{max}, \beta_{min},\beta_{max}, \delta_{min},\delta_{max}, \gamma_{min},\gamma_{max})$ que devra utiliser la fonction. Il est primordial, pour obtenir des temps d'exécution raisonnables, d'utiliser au maximum, les différentes possibilités de vectorisation que fournit la bibliothèque **numpy** :

In [ ]:
def most_stable(x0, y0, args, time, n): # version alpha
  """return set of parameters for maximum stability of the Lotcka/Volterra model for given (x0,y0)"""
  # TODO

In [ ]:
def most_stable(x0, y0, args, time, n): # version finale
  """return set of parameters for maximum stability of the Lotcka/Volterra model for given (x0,y0)"""
  # TODO

Tester la fonction en mettant comme domaine de recherche $(\alpha, \beta, \delta, \gamma) \in [0.1,2.1]^4$ :

In [ ]:
x0, y0, args, time, n = 10, 2, 4*(0.1,2.1), 20, 200 # définition des paramètres pour l'optimisation
args = most_stable(x0, y0, args, time, n) # recherche du minimum de variance
args # il y a plusieurs configurations qui génèrent une variance nulle

In [ ]:
t, x, y = lovo_rk4(x0, y0, args, time, n) # on calcule l'évolution sur le jeu de paramètres trouvé
show_lovo(t, x, y, args) # et on visualise le résultat...

<h2 style="padding:0 0 8px; margin:0 -20px; color:#FFF; background:#07D; text-align:right">● ● ●</h3>